/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAINonUEN2MessagesSubscriptionsCollectionDocumentApiHandler_H
#define OAI_OAINonUEN2MessagesSubscriptionsCollectionDocumentApiHandler_H

#include <QObject>

#include "OAINonUeN2InfoSubscriptionCreateData.h"
#include "OAINonUeN2InfoSubscriptionCreatedData.h"
#include "OAIProblemDetails.h"
#include "OAIRedirectResponse.h"
#include <QString>

namespace OpenAPI {

class OAINonUEN2MessagesSubscriptionsCollectionDocumentApiHandler : public QObject
{
    Q_OBJECT

public:
    OAINonUEN2MessagesSubscriptionsCollectionDocumentApiHandler();
    virtual ~OAINonUEN2MessagesSubscriptionsCollectionDocumentApiHandler();


public slots:
    virtual void nonUeN2InfoSubscribe(OAINonUeN2InfoSubscriptionCreateData oai_non_ue_n2_info_subscription_create_data);
    

};

}

#endif // OAI_OAINonUEN2MessagesSubscriptionsCollectionDocumentApiHandler_H
