/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiHandler.h"
#include "OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiRequest.h"

namespace OpenAPI {

OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiHandler::OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiHandler(){

}

OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiHandler::~OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiHandler(){

}

void OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiHandler::nonUeN2InfoUnSubscribe(QString n2_notify_subscription_id) {
    Q_UNUSED(n2_notify_subscription_id);
    auto reqObj = qobject_cast<OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiRequest*>(sender());
    if( reqObj != nullptr )
    {
        
        reqObj->nonUeN2InfoUnSubscribeResponse();
    }
}


}
