/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAmfEventArea.h
 *
 * 
 */

#ifndef OAIAmfEventArea_H
#define OAIAmfEventArea_H

#include <QJsonObject>

#include "OAILadnInfo.h"
#include "OAIPresenceInfo.h"
#include "OAISnssai.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIAmfEventArea : public OAIObject {
public:
    OAIAmfEventArea();
    OAIAmfEventArea(QString json);
    ~OAIAmfEventArea() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIPresenceInfo getPresenceInfo() const;
    void setPresenceInfo(const OAIPresenceInfo &presence_info);
    bool is_presence_info_Set() const;
    bool is_presence_info_Valid() const;

    OAILadnInfo getLadnInfo() const;
    void setLadnInfo(const OAILadnInfo &ladn_info);
    bool is_ladn_info_Set() const;
    bool is_ladn_info_Valid() const;

    OAISnssai getSNssai() const;
    void setSNssai(const OAISnssai &s_nssai);
    bool is_s_nssai_Set() const;
    bool is_s_nssai_Valid() const;

    QString getNsiId() const;
    void setNsiId(const QString &nsi_id);
    bool is_nsi_id_Set() const;
    bool is_nsi_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIPresenceInfo presence_info;
    bool m_presence_info_isSet;
    bool m_presence_info_isValid;

    OAILadnInfo ladn_info;
    bool m_ladn_info_isSet;
    bool m_ladn_info_isValid;

    OAISnssai s_nssai;
    bool m_s_nssai_isSet;
    bool m_s_nssai_isValid;

    QString nsi_id;
    bool m_nsi_id_isSet;
    bool m_nsi_id_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAmfEventArea)

#endif // OAIAmfEventArea_H
