/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIAmfEventTrigger_anyOf.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIAmfEventTrigger_anyOf::OAIAmfEventTrigger_anyOf(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIAmfEventTrigger_anyOf::OAIAmfEventTrigger_anyOf() {
    this->initializeModel();
}

OAIAmfEventTrigger_anyOf::~OAIAmfEventTrigger_anyOf() {}

void OAIAmfEventTrigger_anyOf::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIAmfEventTrigger_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAIAmfEventTrigger_anyOf::fromJson(QString jsonString) {
    
    if ( jsonString.compare("ONE_TIME", Qt::CaseInsensitive) == 0) {
        m_value = eOAIAmfEventTrigger_anyOf::ONE_TIME;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("CONTINUOUS", Qt::CaseInsensitive) == 0) {
        m_value = eOAIAmfEventTrigger_anyOf::CONTINUOUS;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("PERIODIC", Qt::CaseInsensitive) == 0) {
        m_value = eOAIAmfEventTrigger_anyOf::PERIODIC;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAIAmfEventTrigger_anyOf::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString OAIAmfEventTrigger_anyOf::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAIAmfEventTrigger_anyOf::ONE_TIME:
            val = "ONE_TIME";
            break;
        case eOAIAmfEventTrigger_anyOf::CONTINUOUS:
            val = "CONTINUOUS";
            break;
        case eOAIAmfEventTrigger_anyOf::PERIODIC:
            val = "PERIODIC";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAIAmfEventTrigger_anyOf::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIAmfEventTrigger_anyOf::eOAIAmfEventTrigger_anyOf OAIAmfEventTrigger_anyOf::getValue() const {
    return m_value;
}

void OAIAmfEventTrigger_anyOf::setValue(const OAIAmfEventTrigger_anyOf::eOAIAmfEventTrigger_anyOf& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAIAmfEventTrigger_anyOf::isSet() const {
    
    return m_value_isSet;
}

bool OAIAmfEventTrigger_anyOf::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
