/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAmfEventTrigger_anyOf.h
 *
 * 
 */

#ifndef OAIAmfEventTrigger_anyOf_H
#define OAIAmfEventTrigger_anyOf_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIAmfEventTrigger_anyOf : public OAIEnum {
public:
    OAIAmfEventTrigger_anyOf();
    OAIAmfEventTrigger_anyOf(QString json);
    ~OAIAmfEventTrigger_anyOf() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAIAmfEventTrigger_anyOf {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        ONE_TIME, 
        CONTINUOUS, 
        PERIODIC
    };
    OAIAmfEventTrigger_anyOf::eOAIAmfEventTrigger_anyOf getValue() const;
    void setValue(const OAIAmfEventTrigger_anyOf::eOAIAmfEventTrigger_anyOf& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAIAmfEventTrigger_anyOf m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAmfEventTrigger_anyOf)

#endif // OAIAmfEventTrigger_anyOf_H
