/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIGeraLocation.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIGeraLocation::OAIGeraLocation(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIGeraLocation::OAIGeraLocation() {
    this->initializeModel();
}

OAIGeraLocation::~OAIGeraLocation() {}

void OAIGeraLocation::initializeModel() {

    m_location_number_isSet = false;
    m_location_number_isValid = false;

    m_cgi_isSet = false;
    m_cgi_isValid = false;

    m_rai_isSet = false;
    m_rai_isValid = false;

    m_sai_isSet = false;
    m_sai_isValid = false;

    m_lai_isSet = false;
    m_lai_isValid = false;

    m_vlr_number_isSet = false;
    m_vlr_number_isValid = false;

    m_msc_number_isSet = false;
    m_msc_number_isValid = false;

    m_age_of_location_information_isSet = false;
    m_age_of_location_information_isValid = false;

    m_ue_location_timestamp_isSet = false;
    m_ue_location_timestamp_isValid = false;

    m_geographical_information_isSet = false;
    m_geographical_information_isValid = false;

    m_geodetic_information_isSet = false;
    m_geodetic_information_isValid = false;
}

void OAIGeraLocation::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIGeraLocation::fromJsonObject(QJsonObject json) {

    m_location_number_isValid = ::OpenAPI::fromJsonValue(location_number, json[QString("locationNumber")]);
    m_location_number_isSet = !json[QString("locationNumber")].isNull() && m_location_number_isValid;

    m_cgi_isValid = ::OpenAPI::fromJsonValue(cgi, json[QString("cgi")]);
    m_cgi_isSet = !json[QString("cgi")].isNull() && m_cgi_isValid;

    m_rai_isValid = ::OpenAPI::fromJsonValue(rai, json[QString("rai")]);
    m_rai_isSet = !json[QString("rai")].isNull() && m_rai_isValid;

    m_sai_isValid = ::OpenAPI::fromJsonValue(sai, json[QString("sai")]);
    m_sai_isSet = !json[QString("sai")].isNull() && m_sai_isValid;

    m_lai_isValid = ::OpenAPI::fromJsonValue(lai, json[QString("lai")]);
    m_lai_isSet = !json[QString("lai")].isNull() && m_lai_isValid;

    m_vlr_number_isValid = ::OpenAPI::fromJsonValue(vlr_number, json[QString("vlrNumber")]);
    m_vlr_number_isSet = !json[QString("vlrNumber")].isNull() && m_vlr_number_isValid;

    m_msc_number_isValid = ::OpenAPI::fromJsonValue(msc_number, json[QString("mscNumber")]);
    m_msc_number_isSet = !json[QString("mscNumber")].isNull() && m_msc_number_isValid;

    m_age_of_location_information_isValid = ::OpenAPI::fromJsonValue(age_of_location_information, json[QString("ageOfLocationInformation")]);
    m_age_of_location_information_isSet = !json[QString("ageOfLocationInformation")].isNull() && m_age_of_location_information_isValid;

    m_ue_location_timestamp_isValid = ::OpenAPI::fromJsonValue(ue_location_timestamp, json[QString("ueLocationTimestamp")]);
    m_ue_location_timestamp_isSet = !json[QString("ueLocationTimestamp")].isNull() && m_ue_location_timestamp_isValid;

    m_geographical_information_isValid = ::OpenAPI::fromJsonValue(geographical_information, json[QString("geographicalInformation")]);
    m_geographical_information_isSet = !json[QString("geographicalInformation")].isNull() && m_geographical_information_isValid;

    m_geodetic_information_isValid = ::OpenAPI::fromJsonValue(geodetic_information, json[QString("geodeticInformation")]);
    m_geodetic_information_isSet = !json[QString("geodeticInformation")].isNull() && m_geodetic_information_isValid;
}

QString OAIGeraLocation::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIGeraLocation::asJsonObject() const {
    QJsonObject obj;
    if (m_location_number_isSet) {
        obj.insert(QString("locationNumber"), ::OpenAPI::toJsonValue(location_number));
    }
    if (cgi.isSet()) {
        obj.insert(QString("cgi"), ::OpenAPI::toJsonValue(cgi));
    }
    if (rai.isSet()) {
        obj.insert(QString("rai"), ::OpenAPI::toJsonValue(rai));
    }
    if (sai.isSet()) {
        obj.insert(QString("sai"), ::OpenAPI::toJsonValue(sai));
    }
    if (lai.isSet()) {
        obj.insert(QString("lai"), ::OpenAPI::toJsonValue(lai));
    }
    if (m_vlr_number_isSet) {
        obj.insert(QString("vlrNumber"), ::OpenAPI::toJsonValue(vlr_number));
    }
    if (m_msc_number_isSet) {
        obj.insert(QString("mscNumber"), ::OpenAPI::toJsonValue(msc_number));
    }
    if (m_age_of_location_information_isSet) {
        obj.insert(QString("ageOfLocationInformation"), ::OpenAPI::toJsonValue(age_of_location_information));
    }
    if (m_ue_location_timestamp_isSet) {
        obj.insert(QString("ueLocationTimestamp"), ::OpenAPI::toJsonValue(ue_location_timestamp));
    }
    if (m_geographical_information_isSet) {
        obj.insert(QString("geographicalInformation"), ::OpenAPI::toJsonValue(geographical_information));
    }
    if (m_geodetic_information_isSet) {
        obj.insert(QString("geodeticInformation"), ::OpenAPI::toJsonValue(geodetic_information));
    }
    return obj;
}

QString OAIGeraLocation::getLocationNumber() const {
    return location_number;
}
void OAIGeraLocation::setLocationNumber(const QString &location_number) {
    this->location_number = location_number;
    this->m_location_number_isSet = true;
}

bool OAIGeraLocation::is_location_number_Set() const{
    return m_location_number_isSet;
}

bool OAIGeraLocation::is_location_number_Valid() const{
    return m_location_number_isValid;
}

OAICellGlobalId OAIGeraLocation::getCgi() const {
    return cgi;
}
void OAIGeraLocation::setCgi(const OAICellGlobalId &cgi) {
    this->cgi = cgi;
    this->m_cgi_isSet = true;
}

bool OAIGeraLocation::is_cgi_Set() const{
    return m_cgi_isSet;
}

bool OAIGeraLocation::is_cgi_Valid() const{
    return m_cgi_isValid;
}

OAIRoutingAreaId OAIGeraLocation::getRai() const {
    return rai;
}
void OAIGeraLocation::setRai(const OAIRoutingAreaId &rai) {
    this->rai = rai;
    this->m_rai_isSet = true;
}

bool OAIGeraLocation::is_rai_Set() const{
    return m_rai_isSet;
}

bool OAIGeraLocation::is_rai_Valid() const{
    return m_rai_isValid;
}

OAIServiceAreaId OAIGeraLocation::getSai() const {
    return sai;
}
void OAIGeraLocation::setSai(const OAIServiceAreaId &sai) {
    this->sai = sai;
    this->m_sai_isSet = true;
}

bool OAIGeraLocation::is_sai_Set() const{
    return m_sai_isSet;
}

bool OAIGeraLocation::is_sai_Valid() const{
    return m_sai_isValid;
}

OAILocationAreaId OAIGeraLocation::getLai() const {
    return lai;
}
void OAIGeraLocation::setLai(const OAILocationAreaId &lai) {
    this->lai = lai;
    this->m_lai_isSet = true;
}

bool OAIGeraLocation::is_lai_Set() const{
    return m_lai_isSet;
}

bool OAIGeraLocation::is_lai_Valid() const{
    return m_lai_isValid;
}

QString OAIGeraLocation::getVlrNumber() const {
    return vlr_number;
}
void OAIGeraLocation::setVlrNumber(const QString &vlr_number) {
    this->vlr_number = vlr_number;
    this->m_vlr_number_isSet = true;
}

bool OAIGeraLocation::is_vlr_number_Set() const{
    return m_vlr_number_isSet;
}

bool OAIGeraLocation::is_vlr_number_Valid() const{
    return m_vlr_number_isValid;
}

QString OAIGeraLocation::getMscNumber() const {
    return msc_number;
}
void OAIGeraLocation::setMscNumber(const QString &msc_number) {
    this->msc_number = msc_number;
    this->m_msc_number_isSet = true;
}

bool OAIGeraLocation::is_msc_number_Set() const{
    return m_msc_number_isSet;
}

bool OAIGeraLocation::is_msc_number_Valid() const{
    return m_msc_number_isValid;
}

qint32 OAIGeraLocation::getAgeOfLocationInformation() const {
    return age_of_location_information;
}
void OAIGeraLocation::setAgeOfLocationInformation(const qint32 &age_of_location_information) {
    this->age_of_location_information = age_of_location_information;
    this->m_age_of_location_information_isSet = true;
}

bool OAIGeraLocation::is_age_of_location_information_Set() const{
    return m_age_of_location_information_isSet;
}

bool OAIGeraLocation::is_age_of_location_information_Valid() const{
    return m_age_of_location_information_isValid;
}

QDateTime OAIGeraLocation::getUeLocationTimestamp() const {
    return ue_location_timestamp;
}
void OAIGeraLocation::setUeLocationTimestamp(const QDateTime &ue_location_timestamp) {
    this->ue_location_timestamp = ue_location_timestamp;
    this->m_ue_location_timestamp_isSet = true;
}

bool OAIGeraLocation::is_ue_location_timestamp_Set() const{
    return m_ue_location_timestamp_isSet;
}

bool OAIGeraLocation::is_ue_location_timestamp_Valid() const{
    return m_ue_location_timestamp_isValid;
}

QString OAIGeraLocation::getGeographicalInformation() const {
    return geographical_information;
}
void OAIGeraLocation::setGeographicalInformation(const QString &geographical_information) {
    this->geographical_information = geographical_information;
    this->m_geographical_information_isSet = true;
}

bool OAIGeraLocation::is_geographical_information_Set() const{
    return m_geographical_information_isSet;
}

bool OAIGeraLocation::is_geographical_information_Valid() const{
    return m_geographical_information_isValid;
}

QString OAIGeraLocation::getGeodeticInformation() const {
    return geodetic_information;
}
void OAIGeraLocation::setGeodeticInformation(const QString &geodetic_information) {
    this->geodetic_information = geodetic_information;
    this->m_geodetic_information_isSet = true;
}

bool OAIGeraLocation::is_geodetic_information_Set() const{
    return m_geodetic_information_isSet;
}

bool OAIGeraLocation::is_geodetic_information_Valid() const{
    return m_geodetic_information_isValid;
}

bool OAIGeraLocation::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_location_number_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (cgi.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (rai.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (sai.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (lai.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_vlr_number_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_msc_number_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_age_of_location_information_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_ue_location_timestamp_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_geographical_information_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_geodetic_information_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIGeraLocation::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
