/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIGuami.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIGuami::OAIGuami(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIGuami::OAIGuami() {
    this->initializeModel();
}

OAIGuami::~OAIGuami() {}

void OAIGuami::initializeModel() {

    m_plmn_id_isSet = false;
    m_plmn_id_isValid = false;

    m_amf_id_isSet = false;
    m_amf_id_isValid = false;
}

void OAIGuami::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIGuami::fromJsonObject(QJsonObject json) {

    m_plmn_id_isValid = ::OpenAPI::fromJsonValue(plmn_id, json[QString("plmnId")]);
    m_plmn_id_isSet = !json[QString("plmnId")].isNull() && m_plmn_id_isValid;

    m_amf_id_isValid = ::OpenAPI::fromJsonValue(amf_id, json[QString("amfId")]);
    m_amf_id_isSet = !json[QString("amfId")].isNull() && m_amf_id_isValid;
}

QString OAIGuami::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIGuami::asJsonObject() const {
    QJsonObject obj;
    if (plmn_id.isSet()) {
        obj.insert(QString("plmnId"), ::OpenAPI::toJsonValue(plmn_id));
    }
    if (m_amf_id_isSet) {
        obj.insert(QString("amfId"), ::OpenAPI::toJsonValue(amf_id));
    }
    return obj;
}

OAIPlmnIdNid OAIGuami::getPlmnId() const {
    return plmn_id;
}
void OAIGuami::setPlmnId(const OAIPlmnIdNid &plmn_id) {
    this->plmn_id = plmn_id;
    this->m_plmn_id_isSet = true;
}

bool OAIGuami::is_plmn_id_Set() const{
    return m_plmn_id_isSet;
}

bool OAIGuami::is_plmn_id_Valid() const{
    return m_plmn_id_isValid;
}

QString OAIGuami::getAmfId() const {
    return amf_id;
}
void OAIGuami::setAmfId(const QString &amf_id) {
    this->amf_id = amf_id;
    this->m_amf_id_isSet = true;
}

bool OAIGuami::is_amf_id_Set() const{
    return m_amf_id_isSet;
}

bool OAIGuami::is_amf_id_Valid() const{
    return m_amf_id_isValid;
}

bool OAIGuami::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (plmn_id.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_amf_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIGuami::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_plmn_id_isValid && m_amf_id_isValid && true;
}

} // namespace OpenAPI
