/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAILocationFilter_anyOf.h
 *
 * 
 */

#ifndef OAILocationFilter_anyOf_H
#define OAILocationFilter_anyOf_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAILocationFilter_anyOf : public OAIEnum {
public:
    OAILocationFilter_anyOf();
    OAILocationFilter_anyOf(QString json);
    ~OAILocationFilter_anyOf() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAILocationFilter_anyOf {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        TAI, 
        CELL_ID, 
        N3IWF, 
        UE_IP, 
        UDP_PORT, 
        TNAP_ID, 
        GLI, 
        TWAP_ID
    };
    OAILocationFilter_anyOf::eOAILocationFilter_anyOf getValue() const;
    void setValue(const OAILocationFilter_anyOf::eOAILocationFilter_anyOf& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAILocationFilter_anyOf m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAILocationFilter_anyOf)

#endif // OAILocationFilter_anyOf_H
