/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAILocationAreaId.h
 *
 * 
 */

#ifndef OAILocationAreaId_H
#define OAILocationAreaId_H

#include <QJsonObject>

#include "OAIPlmnId.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAILocationAreaId : public OAIObject {
public:
    OAILocationAreaId();
    OAILocationAreaId(QString json);
    ~OAILocationAreaId() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIPlmnId getPlmnId() const;
    void setPlmnId(const OAIPlmnId &plmn_id);
    bool is_plmn_id_Set() const;
    bool is_plmn_id_Valid() const;

    QString getLac() const;
    void setLac(const QString &lac);
    bool is_lac_Set() const;
    bool is_lac_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIPlmnId plmn_id;
    bool m_plmn_id_isSet;
    bool m_plmn_id_isValid;

    QString lac;
    bool m_lac_isSet;
    bool m_lac_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAILocationAreaId)

#endif // OAILocationAreaId_H
