/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAINFType_anyOf.h
 *
 * 
 */

#ifndef OAINFType_anyOf_H
#define OAINFType_anyOf_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAINFType_anyOf : public OAIEnum {
public:
    OAINFType_anyOf();
    OAINFType_anyOf(QString json);
    ~OAINFType_anyOf() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAINFType_anyOf {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        NRF, 
        UDM, 
        AMF, 
        SMF, 
        AUSF, 
        NEF, 
        PCF, 
        SMSF, 
        NSSF, 
        UDR, 
        LMF, 
        GMLC, 
        _5G_EIR, 
        SEPP, 
        UPF, 
        N3IWF, 
        AF, 
        UDSF, 
        BSF, 
        CHF, 
        NWDAF, 
        PCSCF, 
        CBCF, 
        HSS, 
        UCMF, 
        SOR_AF, 
        SPAF, 
        MME, 
        SCSAS, 
        SCEF, 
        SCP, 
        NSSAAF, 
        ICSCF, 
        SCSCF, 
        DRA, 
        IMS_AS
    };
    OAINFType_anyOf::eOAINFType_anyOf getValue() const;
    void setValue(const OAINFType_anyOf::eOAINFType_anyOf& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAINFType_anyOf m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAINFType_anyOf)

#endif // OAINFType_anyOf_H
