/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIProblemDetails.h
 *
 * 
 */

#ifndef OAIProblemDetails_H
#define OAIProblemDetails_H

#include <QJsonObject>

#include "OAIAccessTokenErr.h"
#include "OAIAccessTokenReq.h"
#include "OAIInvalidParam.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIProblemDetails : public OAIObject {
public:
    OAIProblemDetails();
    OAIProblemDetails(QString json);
    ~OAIProblemDetails() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getType() const;
    void setType(const QString &type);
    bool is_type_Set() const;
    bool is_type_Valid() const;

    QString getTitle() const;
    void setTitle(const QString &title);
    bool is_title_Set() const;
    bool is_title_Valid() const;

    qint32 getStatus() const;
    void setStatus(const qint32 &status);
    bool is_status_Set() const;
    bool is_status_Valid() const;

    QString getDetail() const;
    void setDetail(const QString &detail);
    bool is_detail_Set() const;
    bool is_detail_Valid() const;

    QString getInstance() const;
    void setInstance(const QString &instance);
    bool is_instance_Set() const;
    bool is_instance_Valid() const;

    QString getCause() const;
    void setCause(const QString &cause);
    bool is_cause_Set() const;
    bool is_cause_Valid() const;

    QList<OAIInvalidParam> getInvalidParams() const;
    void setInvalidParams(const QList<OAIInvalidParam> &invalid_params);
    bool is_invalid_params_Set() const;
    bool is_invalid_params_Valid() const;

    QString getSupportedFeatures() const;
    void setSupportedFeatures(const QString &supported_features);
    bool is_supported_features_Set() const;
    bool is_supported_features_Valid() const;

    OAIAccessTokenErr getAccessTokenError() const;
    void setAccessTokenError(const OAIAccessTokenErr &access_token_error);
    bool is_access_token_error_Set() const;
    bool is_access_token_error_Valid() const;

    OAIAccessTokenReq getAccessTokenRequest() const;
    void setAccessTokenRequest(const OAIAccessTokenReq &access_token_request);
    bool is_access_token_request_Set() const;
    bool is_access_token_request_Valid() const;

    QString getNrfId() const;
    void setNrfId(const QString &nrf_id);
    bool is_nrf_id_Set() const;
    bool is_nrf_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString type;
    bool m_type_isSet;
    bool m_type_isValid;

    QString title;
    bool m_title_isSet;
    bool m_title_isValid;

    qint32 status;
    bool m_status_isSet;
    bool m_status_isValid;

    QString detail;
    bool m_detail_isSet;
    bool m_detail_isValid;

    QString instance;
    bool m_instance_isSet;
    bool m_instance_isValid;

    QString cause;
    bool m_cause_isSet;
    bool m_cause_isValid;

    QList<OAIInvalidParam> invalid_params;
    bool m_invalid_params_isSet;
    bool m_invalid_params_isValid;

    QString supported_features;
    bool m_supported_features_isSet;
    bool m_supported_features_isValid;

    OAIAccessTokenErr access_token_error;
    bool m_access_token_error_isSet;
    bool m_access_token_error_isValid;

    OAIAccessTokenReq access_token_request;
    bool m_access_token_request_isSet;
    bool m_access_token_request_isValid;

    QString nrf_id;
    bool m_nrf_id_isSet;
    bool m_nrf_id_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIProblemDetails)

#endif // OAIProblemDetails_H
