/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAITransportProtocol_anyOf.h
 *
 * 
 */

#ifndef OAITransportProtocol_anyOf_H
#define OAITransportProtocol_anyOf_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAITransportProtocol_anyOf : public OAIEnum {
public:
    OAITransportProtocol_anyOf();
    OAITransportProtocol_anyOf(QString json);
    ~OAITransportProtocol_anyOf() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAITransportProtocol_anyOf {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        UDP, 
        TCP
    };
    OAITransportProtocol_anyOf::eOAITransportProtocol_anyOf getValue() const;
    void setValue(const OAITransportProtocol_anyOf::eOAITransportProtocol_anyOf& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAITransportProtocol_anyOf m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAITransportProtocol_anyOf)

#endif // OAITransportProtocol_anyOf_H
