/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAITnapId.h
 *
 * 
 */

#ifndef OAITnapId_H
#define OAITnapId_H

#include <QJsonObject>

#include <QByteArray>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAITnapId : public OAIObject {
public:
    OAITnapId();
    OAITnapId(QString json);
    ~OAITnapId() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getSsId() const;
    void setSsId(const QString &ss_id);
    bool is_ss_id_Set() const;
    bool is_ss_id_Valid() const;

    QString getBssId() const;
    void setBssId(const QString &bss_id);
    bool is_bss_id_Set() const;
    bool is_bss_id_Valid() const;

    QByteArray getCivicAddress() const;
    void setCivicAddress(const QByteArray &civic_address);
    bool is_civic_address_Set() const;
    bool is_civic_address_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString ss_id;
    bool m_ss_id_isSet;
    bool m_ss_id_isValid;

    QString bss_id;
    bool m_bss_id_isSet;
    bool m_bss_id_isValid;

    QByteArray civic_address;
    bool m_civic_address_isSet;
    bool m_civic_address_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAITnapId)

#endif // OAITnapId_H
