/*
 * Namf_Communication
 *
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfcommunication

import (
"amf.com/amfcommon"
"amf.com/amfmodel"
	"context"
	"net/http"
	"errors"
)

// NonUEN2MessagesSubscriptionsCollectionDocumentApiService is a service that implements the logic for the NonUEN2MessagesSubscriptionsCollectionDocumentApiServicer
// This service should implement the business logic for every endpoint for the NonUEN2MessagesSubscriptionsCollectionDocumentApi API.
// Include any external packages or services that will be required by this service.
type NonUEN2MessagesSubscriptionsCollectionDocumentApiService struct {
}

// NewNonUEN2MessagesSubscriptionsCollectionDocumentApiService creates a default api service
func NewNonUEN2MessagesSubscriptionsCollectionDocumentApiService() NonUEN2MessagesSubscriptionsCollectionDocumentApiServicer {
	return &NonUEN2MessagesSubscriptionsCollectionDocumentApiService{}
}

// NonUeN2InfoSubscribe - Namf_Communication Non UE N2 Info Subscribe service Operation
func (s *NonUEN2MessagesSubscriptionsCollectionDocumentApiService) NonUeN2InfoSubscribe(ctx context.Context, nonUeN2InfoSubscriptionCreateData amfmodel.NonUeN2InfoSubscriptionCreateData) (amfcommon.ImplResponse, error) {
	// TODO - update NonUeN2InfoSubscribe with the required logic for this service method.
	// Add api_non_uen2_messages_subscriptions_collection_document_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response amfcommon.Response(201, amfmodel.NonUeN2InfoSubscriptionCreatedData{}) or use other options such as http.Ok ...
	//return amfcommon.Response(201, amfmodel.NonUeN2InfoSubscriptionCreatedData{}), nil

	//TODO: Uncomment the next line to return response amfcommon.Response(307, amfmodel.RedirectResponse{}) or use other options such as http.Ok ...
	//return amfcommon.Response(307, amfmodel.RedirectResponse{}), nil

	//TODO: Uncomment the next line to return response amfcommon.Response(308, amfmodel.RedirectResponse{}) or use other options such as http.Ok ...
	//return amfcommon.Response(308, amfmodel.RedirectResponse{}), nil

	//TODO: Uncomment the next line to return response amfcommon.Response(400, amfmodel.ProblemDetails{}) or use other options such as http.Ok ...
	//return amfcommon.Response(400, amfmodel.ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response amfcommon.Response(403, amfmodel.ProblemDetails{}) or use other options such as http.Ok ...
	//return amfcommon.Response(403, amfmodel.ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response amfcommon.Response(411, amfmodel.ProblemDetails{}) or use other options such as http.Ok ...
	//return amfcommon.Response(411, amfmodel.ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response amfcommon.Response(413, amfmodel.ProblemDetails{}) or use other options such as http.Ok ...
	//return amfcommon.Response(413, amfmodel.ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response amfcommon.Response(415, amfmodel.ProblemDetails{}) or use other options such as http.Ok ...
	//return amfcommon.Response(415, amfmodel.ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response amfcommon.Response(429, amfmodel.ProblemDetails{}) or use other options such as http.Ok ...
	//return amfcommon.Response(429, amfmodel.ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response amfcommon.Response(500, amfmodel.ProblemDetails{}) or use other options such as http.Ok ...
	//return amfcommon.Response(500, amfmodel.ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response amfcommon.Response(503, amfmodel.ProblemDetails{}) or use other options such as http.Ok ...
	//return amfcommon.Response(503, amfmodel.ProblemDetails{}), nil

	//TODO: Uncomment the next line to return response amfcommon.Response(0, amfmodel.{}) or use other options such as http.Ok ...
	//return amfcommon.Response(0, nil),nil

	return amfcommon.Response(http.StatusNotImplemented, nil), errors.New("NonUeN2InfoSubscribe method not implemented")
}
