/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIAssignEbiError.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIAssignEbiError::OAIAssignEbiError(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIAssignEbiError::OAIAssignEbiError() {
    this->initializeModel();
}

OAIAssignEbiError::~OAIAssignEbiError() {}

void OAIAssignEbiError::initializeModel() {

    m_error_isSet = false;
    m_error_isValid = false;

    m_failure_details_isSet = false;
    m_failure_details_isValid = false;
}

void OAIAssignEbiError::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIAssignEbiError::fromJsonObject(QJsonObject json) {

    m_error_isValid = ::OpenAPI::fromJsonValue(error, json[QString("error")]);
    m_error_isSet = !json[QString("error")].isNull() && m_error_isValid;

    m_failure_details_isValid = ::OpenAPI::fromJsonValue(failure_details, json[QString("failureDetails")]);
    m_failure_details_isSet = !json[QString("failureDetails")].isNull() && m_failure_details_isValid;
}

QString OAIAssignEbiError::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIAssignEbiError::asJsonObject() const {
    QJsonObject obj;
    if (error.isSet()) {
        obj.insert(QString("error"), ::OpenAPI::toJsonValue(error));
    }
    if (failure_details.isSet()) {
        obj.insert(QString("failureDetails"), ::OpenAPI::toJsonValue(failure_details));
    }
    return obj;
}

OAIProblemDetails OAIAssignEbiError::getError() const {
    return error;
}
void OAIAssignEbiError::setError(const OAIProblemDetails &error) {
    this->error = error;
    this->m_error_isSet = true;
}

bool OAIAssignEbiError::is_error_Set() const{
    return m_error_isSet;
}

bool OAIAssignEbiError::is_error_Valid() const{
    return m_error_isValid;
}

OAIAssignEbiFailed OAIAssignEbiError::getFailureDetails() const {
    return failure_details;
}
void OAIAssignEbiError::setFailureDetails(const OAIAssignEbiFailed &failure_details) {
    this->failure_details = failure_details;
    this->m_failure_details_isSet = true;
}

bool OAIAssignEbiError::is_failure_details_Set() const{
    return m_failure_details_isSet;
}

bool OAIAssignEbiError::is_failure_details_Valid() const{
    return m_failure_details_isValid;
}

bool OAIAssignEbiError::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (error.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (failure_details.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIAssignEbiError::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_error_isValid && m_failure_details_isValid && true;
}

} // namespace OpenAPI
