/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIAmfStatusChangeNotification.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIAmfStatusChangeNotification::OAIAmfStatusChangeNotification(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIAmfStatusChangeNotification::OAIAmfStatusChangeNotification() {
    this->initializeModel();
}

OAIAmfStatusChangeNotification::~OAIAmfStatusChangeNotification() {}

void OAIAmfStatusChangeNotification::initializeModel() {

    m_amf_status_info_list_isSet = false;
    m_amf_status_info_list_isValid = false;
}

void OAIAmfStatusChangeNotification::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIAmfStatusChangeNotification::fromJsonObject(QJsonObject json) {

    m_amf_status_info_list_isValid = ::OpenAPI::fromJsonValue(amf_status_info_list, json[QString("amfStatusInfoList")]);
    m_amf_status_info_list_isSet = !json[QString("amfStatusInfoList")].isNull() && m_amf_status_info_list_isValid;
}

QString OAIAmfStatusChangeNotification::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIAmfStatusChangeNotification::asJsonObject() const {
    QJsonObject obj;
    if (amf_status_info_list.size() > 0) {
        obj.insert(QString("amfStatusInfoList"), ::OpenAPI::toJsonValue(amf_status_info_list));
    }
    return obj;
}

QList<OAIAmfStatusInfo> OAIAmfStatusChangeNotification::getAmfStatusInfoList() const {
    return amf_status_info_list;
}
void OAIAmfStatusChangeNotification::setAmfStatusInfoList(const QList<OAIAmfStatusInfo> &amf_status_info_list) {
    this->amf_status_info_list = amf_status_info_list;
    this->m_amf_status_info_list_isSet = true;
}

bool OAIAmfStatusChangeNotification::is_amf_status_info_list_Set() const{
    return m_amf_status_info_list_isSet;
}

bool OAIAmfStatusChangeNotification::is_amf_status_info_list_Valid() const{
    return m_amf_status_info_list_isValid;
}

bool OAIAmfStatusChangeNotification::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (amf_status_info_list.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIAmfStatusChangeNotification::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_amf_status_info_list_isValid && true;
}

} // namespace OpenAPI
