/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIAccessType.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIAccessType::OAIAccessType(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIAccessType::OAIAccessType() {
    this->initializeModel();
}

OAIAccessType::~OAIAccessType() {}

void OAIAccessType::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIAccessType::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAIAccessType::fromJson(QString jsonString) {
    
    if ( jsonString.compare("3GPP_ACCESS", Qt::CaseInsensitive) == 0) {
        m_value = eOAIAccessType::_3GPP_ACCESS;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("NON_3GPP_ACCESS", Qt::CaseInsensitive) == 0) {
        m_value = eOAIAccessType::NON_3GPP_ACCESS;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAIAccessType::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString OAIAccessType::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAIAccessType::_3GPP_ACCESS:
            val = "3GPP_ACCESS";
            break;
        case eOAIAccessType::NON_3GPP_ACCESS:
            val = "NON_3GPP_ACCESS";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAIAccessType::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIAccessType::eOAIAccessType OAIAccessType::getValue() const {
    return m_value;
}

void OAIAccessType::setValue(const OAIAccessType::eOAIAccessType& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAIAccessType::isSet() const {
    
    return m_value_isSet;
}

bool OAIAccessType::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
