/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICipheringAlgorithm_anyOf.h
 *
 * 
 */

#ifndef OAICipheringAlgorithm_anyOf_H
#define OAICipheringAlgorithm_anyOf_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAICipheringAlgorithm_anyOf : public OAIEnum {
public:
    OAICipheringAlgorithm_anyOf();
    OAICipheringAlgorithm_anyOf(QString json);
    ~OAICipheringAlgorithm_anyOf() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAICipheringAlgorithm_anyOf {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        NEA0, 
        NEA1, 
        NEA2, 
        NEA3
    };
    OAICipheringAlgorithm_anyOf::eOAICipheringAlgorithm_anyOf getValue() const;
    void setValue(const OAICipheringAlgorithm_anyOf::eOAICipheringAlgorithm_anyOf& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAICipheringAlgorithm_anyOf m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAICipheringAlgorithm_anyOf)

#endif // OAICipheringAlgorithm_anyOf_H
