/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIConfiguredSnssai.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIConfiguredSnssai::OAIConfiguredSnssai(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIConfiguredSnssai::OAIConfiguredSnssai() {
    this->initializeModel();
}

OAIConfiguredSnssai::~OAIConfiguredSnssai() {}

void OAIConfiguredSnssai::initializeModel() {

    m_configured_snssai_isSet = false;
    m_configured_snssai_isValid = false;

    m_mapped_home_snssai_isSet = false;
    m_mapped_home_snssai_isValid = false;
}

void OAIConfiguredSnssai::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIConfiguredSnssai::fromJsonObject(QJsonObject json) {

    m_configured_snssai_isValid = ::OpenAPI::fromJsonValue(configured_snssai, json[QString("configuredSnssai")]);
    m_configured_snssai_isSet = !json[QString("configuredSnssai")].isNull() && m_configured_snssai_isValid;

    m_mapped_home_snssai_isValid = ::OpenAPI::fromJsonValue(mapped_home_snssai, json[QString("mappedHomeSnssai")]);
    m_mapped_home_snssai_isSet = !json[QString("mappedHomeSnssai")].isNull() && m_mapped_home_snssai_isValid;
}

QString OAIConfiguredSnssai::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIConfiguredSnssai::asJsonObject() const {
    QJsonObject obj;
    if (configured_snssai.isSet()) {
        obj.insert(QString("configuredSnssai"), ::OpenAPI::toJsonValue(configured_snssai));
    }
    if (mapped_home_snssai.isSet()) {
        obj.insert(QString("mappedHomeSnssai"), ::OpenAPI::toJsonValue(mapped_home_snssai));
    }
    return obj;
}

OAISnssai OAIConfiguredSnssai::getConfiguredSnssai() const {
    return configured_snssai;
}
void OAIConfiguredSnssai::setConfiguredSnssai(const OAISnssai &configured_snssai) {
    this->configured_snssai = configured_snssai;
    this->m_configured_snssai_isSet = true;
}

bool OAIConfiguredSnssai::is_configured_snssai_Set() const{
    return m_configured_snssai_isSet;
}

bool OAIConfiguredSnssai::is_configured_snssai_Valid() const{
    return m_configured_snssai_isValid;
}

OAISnssai OAIConfiguredSnssai::getMappedHomeSnssai() const {
    return mapped_home_snssai;
}
void OAIConfiguredSnssai::setMappedHomeSnssai(const OAISnssai &mapped_home_snssai) {
    this->mapped_home_snssai = mapped_home_snssai;
    this->m_mapped_home_snssai_isSet = true;
}

bool OAIConfiguredSnssai::is_mapped_home_snssai_Set() const{
    return m_mapped_home_snssai_isSet;
}

bool OAIConfiguredSnssai::is_mapped_home_snssai_Valid() const{
    return m_mapped_home_snssai_isValid;
}

bool OAIConfiguredSnssai::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (configured_snssai.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (mapped_home_snssai.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIConfiguredSnssai::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_configured_snssai_isValid && true;
}

} // namespace OpenAPI
