/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAICeModeBInd.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAICeModeBInd::OAICeModeBInd(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAICeModeBInd::OAICeModeBInd() {
    this->initializeModel();
}

OAICeModeBInd::~OAICeModeBInd() {}

void OAICeModeBInd::initializeModel() {

    m_ce_mode_b_support_ind_isSet = false;
    m_ce_mode_b_support_ind_isValid = false;
}

void OAICeModeBInd::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAICeModeBInd::fromJsonObject(QJsonObject json) {

    m_ce_mode_b_support_ind_isValid = ::OpenAPI::fromJsonValue(ce_mode_b_support_ind, json[QString("ceModeBSupportInd")]);
    m_ce_mode_b_support_ind_isSet = !json[QString("ceModeBSupportInd")].isNull() && m_ce_mode_b_support_ind_isValid;
}

QString OAICeModeBInd::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAICeModeBInd::asJsonObject() const {
    QJsonObject obj;
    if (m_ce_mode_b_support_ind_isSet) {
        obj.insert(QString("ceModeBSupportInd"), ::OpenAPI::toJsonValue(ce_mode_b_support_ind));
    }
    return obj;
}

bool OAICeModeBInd::isCeModeBSupportInd() const {
    return ce_mode_b_support_ind;
}
void OAICeModeBInd::setCeModeBSupportInd(const bool &ce_mode_b_support_ind) {
    this->ce_mode_b_support_ind = ce_mode_b_support_ind;
    this->m_ce_mode_b_support_ind_isSet = true;
}

bool OAICeModeBInd::is_ce_mode_b_support_ind_Set() const{
    return m_ce_mode_b_support_ind_isSet;
}

bool OAICeModeBInd::is_ce_mode_b_support_ind_Valid() const{
    return m_ce_mode_b_support_ind_isValid;
}

bool OAICeModeBInd::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_ce_mode_b_support_ind_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAICeModeBInd::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_ce_mode_b_support_ind_isValid && true;
}

} // namespace OpenAPI
