/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_object_1.h
 *
 * 
 */

#ifndef OAIInline_object_1_H
#define OAIInline_object_1_H

#include <QJsonObject>

#include "OAIHttpFileElement.h"
#include "OAIUeContextRelocateData.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIInline_object_1 : public OAIObject {
public:
    OAIInline_object_1();
    OAIInline_object_1(QString json);
    ~OAIInline_object_1() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIUeContextRelocateData getJsonData() const;
    void setJsonData(const OAIUeContextRelocateData &json_data);
    bool is_json_data_Set() const;
    bool is_json_data_Valid() const;

    OAIHttpFileElement getBinaryDataGtpcMessage() const;
    void setBinaryDataGtpcMessage(const OAIHttpFileElement &binary_data_gtpc_message);
    bool is_binary_data_gtpc_message_Set() const;
    bool is_binary_data_gtpc_message_Valid() const;

    OAIHttpFileElement getBinaryDataN2Information() const;
    void setBinaryDataN2Information(const OAIHttpFileElement &binary_data_n2_information);
    bool is_binary_data_n2_information_Set() const;
    bool is_binary_data_n2_information_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt1() const;
    void setBinaryDataN2InformationExt1(const OAIHttpFileElement &binary_data_n2_information_ext1);
    bool is_binary_data_n2_information_ext1_Set() const;
    bool is_binary_data_n2_information_ext1_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt2() const;
    void setBinaryDataN2InformationExt2(const OAIHttpFileElement &binary_data_n2_information_ext2);
    bool is_binary_data_n2_information_ext2_Set() const;
    bool is_binary_data_n2_information_ext2_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt3() const;
    void setBinaryDataN2InformationExt3(const OAIHttpFileElement &binary_data_n2_information_ext3);
    bool is_binary_data_n2_information_ext3_Set() const;
    bool is_binary_data_n2_information_ext3_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt4() const;
    void setBinaryDataN2InformationExt4(const OAIHttpFileElement &binary_data_n2_information_ext4);
    bool is_binary_data_n2_information_ext4_Set() const;
    bool is_binary_data_n2_information_ext4_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt5() const;
    void setBinaryDataN2InformationExt5(const OAIHttpFileElement &binary_data_n2_information_ext5);
    bool is_binary_data_n2_information_ext5_Set() const;
    bool is_binary_data_n2_information_ext5_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt6() const;
    void setBinaryDataN2InformationExt6(const OAIHttpFileElement &binary_data_n2_information_ext6);
    bool is_binary_data_n2_information_ext6_Set() const;
    bool is_binary_data_n2_information_ext6_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt7() const;
    void setBinaryDataN2InformationExt7(const OAIHttpFileElement &binary_data_n2_information_ext7);
    bool is_binary_data_n2_information_ext7_Set() const;
    bool is_binary_data_n2_information_ext7_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt8() const;
    void setBinaryDataN2InformationExt8(const OAIHttpFileElement &binary_data_n2_information_ext8);
    bool is_binary_data_n2_information_ext8_Set() const;
    bool is_binary_data_n2_information_ext8_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt9() const;
    void setBinaryDataN2InformationExt9(const OAIHttpFileElement &binary_data_n2_information_ext9);
    bool is_binary_data_n2_information_ext9_Set() const;
    bool is_binary_data_n2_information_ext9_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt10() const;
    void setBinaryDataN2InformationExt10(const OAIHttpFileElement &binary_data_n2_information_ext10);
    bool is_binary_data_n2_information_ext10_Set() const;
    bool is_binary_data_n2_information_ext10_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt11() const;
    void setBinaryDataN2InformationExt11(const OAIHttpFileElement &binary_data_n2_information_ext11);
    bool is_binary_data_n2_information_ext11_Set() const;
    bool is_binary_data_n2_information_ext11_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt12() const;
    void setBinaryDataN2InformationExt12(const OAIHttpFileElement &binary_data_n2_information_ext12);
    bool is_binary_data_n2_information_ext12_Set() const;
    bool is_binary_data_n2_information_ext12_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt13() const;
    void setBinaryDataN2InformationExt13(const OAIHttpFileElement &binary_data_n2_information_ext13);
    bool is_binary_data_n2_information_ext13_Set() const;
    bool is_binary_data_n2_information_ext13_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt14() const;
    void setBinaryDataN2InformationExt14(const OAIHttpFileElement &binary_data_n2_information_ext14);
    bool is_binary_data_n2_information_ext14_Set() const;
    bool is_binary_data_n2_information_ext14_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt15() const;
    void setBinaryDataN2InformationExt15(const OAIHttpFileElement &binary_data_n2_information_ext15);
    bool is_binary_data_n2_information_ext15_Set() const;
    bool is_binary_data_n2_information_ext15_Valid() const;

    OAIHttpFileElement getBinaryDataN2InformationExt16() const;
    void setBinaryDataN2InformationExt16(const OAIHttpFileElement &binary_data_n2_information_ext16);
    bool is_binary_data_n2_information_ext16_Set() const;
    bool is_binary_data_n2_information_ext16_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIUeContextRelocateData json_data;
    bool m_json_data_isSet;
    bool m_json_data_isValid;

    OAIHttpFileElement binary_data_gtpc_message;
    bool m_binary_data_gtpc_message_isSet;
    bool m_binary_data_gtpc_message_isValid;

    OAIHttpFileElement binary_data_n2_information;
    bool m_binary_data_n2_information_isSet;
    bool m_binary_data_n2_information_isValid;

    OAIHttpFileElement binary_data_n2_information_ext1;
    bool m_binary_data_n2_information_ext1_isSet;
    bool m_binary_data_n2_information_ext1_isValid;

    OAIHttpFileElement binary_data_n2_information_ext2;
    bool m_binary_data_n2_information_ext2_isSet;
    bool m_binary_data_n2_information_ext2_isValid;

    OAIHttpFileElement binary_data_n2_information_ext3;
    bool m_binary_data_n2_information_ext3_isSet;
    bool m_binary_data_n2_information_ext3_isValid;

    OAIHttpFileElement binary_data_n2_information_ext4;
    bool m_binary_data_n2_information_ext4_isSet;
    bool m_binary_data_n2_information_ext4_isValid;

    OAIHttpFileElement binary_data_n2_information_ext5;
    bool m_binary_data_n2_information_ext5_isSet;
    bool m_binary_data_n2_information_ext5_isValid;

    OAIHttpFileElement binary_data_n2_information_ext6;
    bool m_binary_data_n2_information_ext6_isSet;
    bool m_binary_data_n2_information_ext6_isValid;

    OAIHttpFileElement binary_data_n2_information_ext7;
    bool m_binary_data_n2_information_ext7_isSet;
    bool m_binary_data_n2_information_ext7_isValid;

    OAIHttpFileElement binary_data_n2_information_ext8;
    bool m_binary_data_n2_information_ext8_isSet;
    bool m_binary_data_n2_information_ext8_isValid;

    OAIHttpFileElement binary_data_n2_information_ext9;
    bool m_binary_data_n2_information_ext9_isSet;
    bool m_binary_data_n2_information_ext9_isValid;

    OAIHttpFileElement binary_data_n2_information_ext10;
    bool m_binary_data_n2_information_ext10_isSet;
    bool m_binary_data_n2_information_ext10_isValid;

    OAIHttpFileElement binary_data_n2_information_ext11;
    bool m_binary_data_n2_information_ext11_isSet;
    bool m_binary_data_n2_information_ext11_isValid;

    OAIHttpFileElement binary_data_n2_information_ext12;
    bool m_binary_data_n2_information_ext12_isSet;
    bool m_binary_data_n2_information_ext12_isValid;

    OAIHttpFileElement binary_data_n2_information_ext13;
    bool m_binary_data_n2_information_ext13_isSet;
    bool m_binary_data_n2_information_ext13_isValid;

    OAIHttpFileElement binary_data_n2_information_ext14;
    bool m_binary_data_n2_information_ext14_isSet;
    bool m_binary_data_n2_information_ext14_isValid;

    OAIHttpFileElement binary_data_n2_information_ext15;
    bool m_binary_data_n2_information_ext15_isSet;
    bool m_binary_data_n2_information_ext15_isValid;

    OAIHttpFileElement binary_data_n2_information_ext16;
    bool m_binary_data_n2_information_ext16_isSet;
    bool m_binary_data_n2_information_ext16_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIInline_object_1)

#endif // OAIInline_object_1_H
