/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAILossOfConnectivityReason.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAILossOfConnectivityReason::OAILossOfConnectivityReason(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAILossOfConnectivityReason::OAILossOfConnectivityReason() {
    this->initializeModel();
}

OAILossOfConnectivityReason::~OAILossOfConnectivityReason() {}

void OAILossOfConnectivityReason::initializeModel() {

}

void OAILossOfConnectivityReason::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAILossOfConnectivityReason::fromJsonObject(QJsonObject json) {

}

QString OAILossOfConnectivityReason::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAILossOfConnectivityReason::asJsonObject() const {
    QJsonObject obj;
    return obj;
}

bool OAILossOfConnectivityReason::isSet() const {
    bool isObjectUpdated = false;
    do {

    } while (false);
    return isObjectUpdated;
}

bool OAILossOfConnectivityReason::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
