/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIN2InformationTransferError.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIN2InformationTransferError::OAIN2InformationTransferError(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIN2InformationTransferError::OAIN2InformationTransferError() {
    this->initializeModel();
}

OAIN2InformationTransferError::~OAIN2InformationTransferError() {}

void OAIN2InformationTransferError::initializeModel() {

    m_error_isSet = false;
    m_error_isValid = false;

    m_pws_error_info_isSet = false;
    m_pws_error_info_isValid = false;
}

void OAIN2InformationTransferError::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIN2InformationTransferError::fromJsonObject(QJsonObject json) {

    m_error_isValid = ::OpenAPI::fromJsonValue(error, json[QString("error")]);
    m_error_isSet = !json[QString("error")].isNull() && m_error_isValid;

    m_pws_error_info_isValid = ::OpenAPI::fromJsonValue(pws_error_info, json[QString("pwsErrorInfo")]);
    m_pws_error_info_isSet = !json[QString("pwsErrorInfo")].isNull() && m_pws_error_info_isValid;
}

QString OAIN2InformationTransferError::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIN2InformationTransferError::asJsonObject() const {
    QJsonObject obj;
    if (error.isSet()) {
        obj.insert(QString("error"), ::OpenAPI::toJsonValue(error));
    }
    if (pws_error_info.isSet()) {
        obj.insert(QString("pwsErrorInfo"), ::OpenAPI::toJsonValue(pws_error_info));
    }
    return obj;
}

OAIProblemDetails OAIN2InformationTransferError::getError() const {
    return error;
}
void OAIN2InformationTransferError::setError(const OAIProblemDetails &error) {
    this->error = error;
    this->m_error_isSet = true;
}

bool OAIN2InformationTransferError::is_error_Set() const{
    return m_error_isSet;
}

bool OAIN2InformationTransferError::is_error_Valid() const{
    return m_error_isValid;
}

OAIPWSErrorData OAIN2InformationTransferError::getPwsErrorInfo() const {
    return pws_error_info;
}
void OAIN2InformationTransferError::setPwsErrorInfo(const OAIPWSErrorData &pws_error_info) {
    this->pws_error_info = pws_error_info;
    this->m_pws_error_info_isSet = true;
}

bool OAIN2InformationTransferError::is_pws_error_info_Set() const{
    return m_pws_error_info_isSet;
}

bool OAIN2InformationTransferError::is_pws_error_info_Valid() const{
    return m_pws_error_info_isValid;
}

bool OAIN2InformationTransferError::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (error.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (pws_error_info.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIN2InformationTransferError::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_error_isValid && true;
}

} // namespace OpenAPI
