/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIN1MessageNotification.h
 *
 * 
 */

#ifndef OAIN1MessageNotification_H
#define OAIN1MessageNotification_H

#include <QJsonObject>

#include "OAIEcgi.h"
#include "OAIGuami.h"
#include "OAIN1MessageContainer.h"
#include "OAINcgi.h"
#include "OAIRegistrationContextContainer.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIN1MessageNotification : public OAIObject {
public:
    OAIN1MessageNotification();
    OAIN1MessageNotification(QString json);
    ~OAIN1MessageNotification() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getN1NotifySubscriptionId() const;
    void setN1NotifySubscriptionId(const QString &n1_notify_subscription_id);
    bool is_n1_notify_subscription_id_Set() const;
    bool is_n1_notify_subscription_id_Valid() const;

    OAIN1MessageContainer getN1MessageContainer() const;
    void setN1MessageContainer(const OAIN1MessageContainer &n1_message_container);
    bool is_n1_message_container_Set() const;
    bool is_n1_message_container_Valid() const;

    QString getLcsCorrelationId() const;
    void setLcsCorrelationId(const QString &lcs_correlation_id);
    bool is_lcs_correlation_id_Set() const;
    bool is_lcs_correlation_id_Valid() const;

    OAIRegistrationContextContainer getRegistrationCtxtContainer() const;
    void setRegistrationCtxtContainer(const OAIRegistrationContextContainer &registration_ctxt_container);
    bool is_registration_ctxt_container_Set() const;
    bool is_registration_ctxt_container_Valid() const;

    QString getNewLmfIdentification() const;
    void setNewLmfIdentification(const QString &new_lmf_identification);
    bool is_new_lmf_identification_Set() const;
    bool is_new_lmf_identification_Valid() const;

    OAIGuami getGuami() const;
    void setGuami(const OAIGuami &guami);
    bool is_guami_Set() const;
    bool is_guami_Valid() const;

    bool isCIoT5GsOptimisation() const;
    void setCIoT5GsOptimisation(const bool &c_io_t5_gs_optimisation);
    bool is_c_io_t5_gs_optimisation_Set() const;
    bool is_c_io_t5_gs_optimisation_Valid() const;

    OAIEcgi getEcgi() const;
    void setEcgi(const OAIEcgi &ecgi);
    bool is_ecgi_Set() const;
    bool is_ecgi_Valid() const;

    OAINcgi getNcgi() const;
    void setNcgi(const OAINcgi &ncgi);
    bool is_ncgi_Set() const;
    bool is_ncgi_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString n1_notify_subscription_id;
    bool m_n1_notify_subscription_id_isSet;
    bool m_n1_notify_subscription_id_isValid;

    OAIN1MessageContainer n1_message_container;
    bool m_n1_message_container_isSet;
    bool m_n1_message_container_isValid;

    QString lcs_correlation_id;
    bool m_lcs_correlation_id_isSet;
    bool m_lcs_correlation_id_isValid;

    OAIRegistrationContextContainer registration_ctxt_container;
    bool m_registration_ctxt_container_isSet;
    bool m_registration_ctxt_container_isValid;

    QString new_lmf_identification;
    bool m_new_lmf_identification_isSet;
    bool m_new_lmf_identification_isValid;

    OAIGuami guami;
    bool m_guami_isSet;
    bool m_guami_isValid;

    bool c_io_t5_gs_optimisation;
    bool m_c_io_t5_gs_optimisation_isSet;
    bool m_c_io_t5_gs_optimisation_isValid;

    OAIEcgi ecgi;
    bool m_ecgi_isSet;
    bool m_ecgi_isValid;

    OAINcgi ncgi;
    bool m_ncgi_isSet;
    bool m_ncgi_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIN1MessageNotification)

#endif // OAIN1MessageNotification_H
