/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIN2SmInformation.h
 *
 * 
 */

#ifndef OAIN2SmInformation_H
#define OAIN2SmInformation_H

#include <QJsonObject>

#include "OAIN2InfoContent.h"
#include "OAISnssai.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIN2SmInformation : public OAIObject {
public:
    OAIN2SmInformation();
    OAIN2SmInformation(QString json);
    ~OAIN2SmInformation() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getPduSessionId() const;
    void setPduSessionId(const qint32 &pdu_session_id);
    bool is_pdu_session_id_Set() const;
    bool is_pdu_session_id_Valid() const;

    OAIN2InfoContent getN2InfoContent() const;
    void setN2InfoContent(const OAIN2InfoContent &n2_info_content);
    bool is_n2_info_content_Set() const;
    bool is_n2_info_content_Valid() const;

    OAISnssai getSNssai() const;
    void setSNssai(const OAISnssai &s_nssai);
    bool is_s_nssai_Set() const;
    bool is_s_nssai_Valid() const;

    OAISnssai getHomePlmnSnssai() const;
    void setHomePlmnSnssai(const OAISnssai &home_plmn_snssai);
    bool is_home_plmn_snssai_Set() const;
    bool is_home_plmn_snssai_Valid() const;

    OAISnssai getIwkSnssai() const;
    void setIwkSnssai(const OAISnssai &iwk_snssai);
    bool is_iwk_snssai_Set() const;
    bool is_iwk_snssai_Valid() const;

    bool isSubjectToHo() const;
    void setSubjectToHo(const bool &subject_to_ho);
    bool is_subject_to_ho_Set() const;
    bool is_subject_to_ho_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 pdu_session_id;
    bool m_pdu_session_id_isSet;
    bool m_pdu_session_id_isValid;

    OAIN2InfoContent n2_info_content;
    bool m_n2_info_content_isSet;
    bool m_n2_info_content_isValid;

    OAISnssai s_nssai;
    bool m_s_nssai_isSet;
    bool m_s_nssai_isValid;

    OAISnssai home_plmn_snssai;
    bool m_home_plmn_snssai_isSet;
    bool m_home_plmn_snssai_isValid;

    OAISnssai iwk_snssai;
    bool m_iwk_snssai_isSet;
    bool m_iwk_snssai_isValid;

    bool subject_to_ho;
    bool m_subject_to_ho_isSet;
    bool m_subject_to_ho_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIN2SmInformation)

#endif // OAIN2SmInformation_H
