/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAINasSecurityMode.h
 *
 * 
 */

#ifndef OAINasSecurityMode_H
#define OAINasSecurityMode_H

#include <QJsonObject>

#include "OAICipheringAlgorithm.h"
#include "OAIIntegrityAlgorithm.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAINasSecurityMode : public OAIObject {
public:
    OAINasSecurityMode();
    OAINasSecurityMode(QString json);
    ~OAINasSecurityMode() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIIntegrityAlgorithm getIntegrityAlgorithm() const;
    void setIntegrityAlgorithm(const OAIIntegrityAlgorithm &integrity_algorithm);
    bool is_integrity_algorithm_Set() const;
    bool is_integrity_algorithm_Valid() const;

    OAICipheringAlgorithm getCipheringAlgorithm() const;
    void setCipheringAlgorithm(const OAICipheringAlgorithm &ciphering_algorithm);
    bool is_ciphering_algorithm_Set() const;
    bool is_ciphering_algorithm_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIIntegrityAlgorithm integrity_algorithm;
    bool m_integrity_algorithm_isSet;
    bool m_integrity_algorithm_isValid;

    OAICipheringAlgorithm ciphering_algorithm;
    bool m_ciphering_algorithm_isSet;
    bool m_ciphering_algorithm_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAINasSecurityMode)

#endif // OAINasSecurityMode_H
