/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIN2InformationTransferResult_anyOf.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIN2InformationTransferResult_anyOf::OAIN2InformationTransferResult_anyOf(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIN2InformationTransferResult_anyOf::OAIN2InformationTransferResult_anyOf() {
    this->initializeModel();
}

OAIN2InformationTransferResult_anyOf::~OAIN2InformationTransferResult_anyOf() {}

void OAIN2InformationTransferResult_anyOf::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIN2InformationTransferResult_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAIN2InformationTransferResult_anyOf::fromJson(QString jsonString) {
    
    if ( jsonString.compare("N2_INFO_TRANSFER_INITIATED", Qt::CaseInsensitive) == 0) {
        m_value = eOAIN2InformationTransferResult_anyOf::N2_INFO_TRANSFER_INITIATED;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAIN2InformationTransferResult_anyOf::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString OAIN2InformationTransferResult_anyOf::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAIN2InformationTransferResult_anyOf::N2_INFO_TRANSFER_INITIATED:
            val = "N2_INFO_TRANSFER_INITIATED";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAIN2InformationTransferResult_anyOf::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIN2InformationTransferResult_anyOf::eOAIN2InformationTransferResult_anyOf OAIN2InformationTransferResult_anyOf::getValue() const {
    return m_value;
}

void OAIN2InformationTransferResult_anyOf::setValue(const OAIN2InformationTransferResult_anyOf::eOAIN2InformationTransferResult_anyOf& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAIN2InformationTransferResult_anyOf::isSet() const {
    
    return m_value_isSet;
}

bool OAIN2InformationTransferResult_anyOf::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
