/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIN2InformationClass_anyOf.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIN2InformationClass_anyOf::OAIN2InformationClass_anyOf(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIN2InformationClass_anyOf::OAIN2InformationClass_anyOf() {
    this->initializeModel();
}

OAIN2InformationClass_anyOf::~OAIN2InformationClass_anyOf() {}

void OAIN2InformationClass_anyOf::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIN2InformationClass_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAIN2InformationClass_anyOf::fromJson(QString jsonString) {
    
    if ( jsonString.compare("SM", Qt::CaseInsensitive) == 0) {
        m_value = eOAIN2InformationClass_anyOf::SM;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("NRPPa", Qt::CaseInsensitive) == 0) {
        m_value = eOAIN2InformationClass_anyOf::NRPPA;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("PWS", Qt::CaseInsensitive) == 0) {
        m_value = eOAIN2InformationClass_anyOf::PWS;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("PWS-BCAL", Qt::CaseInsensitive) == 0) {
        m_value = eOAIN2InformationClass_anyOf::PWS_BCAL;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("PWS-RF", Qt::CaseInsensitive) == 0) {
        m_value = eOAIN2InformationClass_anyOf::PWS_RF;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("RAN", Qt::CaseInsensitive) == 0) {
        m_value = eOAIN2InformationClass_anyOf::RAN;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("V2X", Qt::CaseInsensitive) == 0) {
        m_value = eOAIN2InformationClass_anyOf::V2X;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAIN2InformationClass_anyOf::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString OAIN2InformationClass_anyOf::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAIN2InformationClass_anyOf::SM:
            val = "SM";
            break;
        case eOAIN2InformationClass_anyOf::NRPPA:
            val = "NRPPa";
            break;
        case eOAIN2InformationClass_anyOf::PWS:
            val = "PWS";
            break;
        case eOAIN2InformationClass_anyOf::PWS_BCAL:
            val = "PWS-BCAL";
            break;
        case eOAIN2InformationClass_anyOf::PWS_RF:
            val = "PWS-RF";
            break;
        case eOAIN2InformationClass_anyOf::RAN:
            val = "RAN";
            break;
        case eOAIN2InformationClass_anyOf::V2X:
            val = "V2X";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAIN2InformationClass_anyOf::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIN2InformationClass_anyOf::eOAIN2InformationClass_anyOf OAIN2InformationClass_anyOf::getValue() const {
    return m_value;
}

void OAIN2InformationClass_anyOf::setValue(const OAIN2InformationClass_anyOf::eOAIN2InformationClass_anyOf& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAIN2InformationClass_anyOf::isSet() const {
    
    return m_value_isSet;
}

bool OAIN2InformationClass_anyOf::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
