/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIPc5QoSPara.h
 *
 * 
 */

#ifndef OAIPc5QoSPara_H
#define OAIPc5QoSPara_H

#include <QJsonObject>

#include "OAIPc5QosFlowItem.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIPc5QoSPara : public OAIObject {
public:
    OAIPc5QoSPara();
    OAIPc5QoSPara(QString json);
    ~OAIPc5QoSPara() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAIPc5QosFlowItem> getPc5QosFlowList() const;
    void setPc5QosFlowList(const QList<OAIPc5QosFlowItem> &pc5_qos_flow_list);
    bool is_pc5_qos_flow_list_Set() const;
    bool is_pc5_qos_flow_list_Valid() const;

    QString getPc5LinkAmbr() const;
    void setPc5LinkAmbr(const QString &pc5_link_ambr);
    bool is_pc5_link_ambr_Set() const;
    bool is_pc5_link_ambr_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<OAIPc5QosFlowItem> pc5_qos_flow_list;
    bool m_pc5_qos_flow_list_isSet;
    bool m_pc5_qos_flow_list_isValid;

    QString pc5_link_ambr;
    bool m_pc5_link_ambr_isSet;
    bool m_pc5_link_ambr_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIPc5QoSPara)

#endif // OAIPc5QoSPara_H
