/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIPlmnId.h
 *
 * 
 */

#ifndef OAIPlmnId_H
#define OAIPlmnId_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIPlmnId : public OAIObject {
public:
    OAIPlmnId();
    OAIPlmnId(QString json);
    ~OAIPlmnId() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getMcc() const;
    void setMcc(const QString &mcc);
    bool is_mcc_Set() const;
    bool is_mcc_Valid() const;

    QString getMnc() const;
    void setMnc(const QString &mnc);
    bool is_mnc_Set() const;
    bool is_mnc_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString mcc;
    bool m_mcc_isSet;
    bool m_mcc_isValid;

    QString mnc;
    bool m_mnc_isSet;
    bool m_mnc_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIPlmnId)

#endif // OAIPlmnId_H
