/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIReportIntervalMdt_anyOf.h
 *
 * 
 */

#ifndef OAIReportIntervalMdt_anyOf_H
#define OAIReportIntervalMdt_anyOf_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIReportIntervalMdt_anyOf : public OAIEnum {
public:
    OAIReportIntervalMdt_anyOf();
    OAIReportIntervalMdt_anyOf(QString json);
    ~OAIReportIntervalMdt_anyOf() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAIReportIntervalMdt_anyOf {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        _120, 
        _240, 
        _480, 
        _640, 
        _1024, 
        _2048, 
        _5120, 
        _10240, 
        _60000, 
        _360000, 
        _720000, 
        _1800000, 
        _3600000
    };
    OAIReportIntervalMdt_anyOf::eOAIReportIntervalMdt_anyOf getValue() const;
    void setValue(const OAIReportIntervalMdt_anyOf::eOAIReportIntervalMdt_anyOf& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAIReportIntervalMdt_anyOf m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIReportIntervalMdt_anyOf)

#endif // OAIReportIntervalMdt_anyOf_H
