/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIRefToBinaryData.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIRefToBinaryData::OAIRefToBinaryData(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIRefToBinaryData::OAIRefToBinaryData() {
    this->initializeModel();
}

OAIRefToBinaryData::~OAIRefToBinaryData() {}

void OAIRefToBinaryData::initializeModel() {

    m_content_id_isSet = false;
    m_content_id_isValid = false;
}

void OAIRefToBinaryData::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIRefToBinaryData::fromJsonObject(QJsonObject json) {

    m_content_id_isValid = ::OpenAPI::fromJsonValue(content_id, json[QString("contentId")]);
    m_content_id_isSet = !json[QString("contentId")].isNull() && m_content_id_isValid;
}

QString OAIRefToBinaryData::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIRefToBinaryData::asJsonObject() const {
    QJsonObject obj;
    if (m_content_id_isSet) {
        obj.insert(QString("contentId"), ::OpenAPI::toJsonValue(content_id));
    }
    return obj;
}

QString OAIRefToBinaryData::getContentId() const {
    return content_id;
}
void OAIRefToBinaryData::setContentId(const QString &content_id) {
    this->content_id = content_id;
    this->m_content_id_isSet = true;
}

bool OAIRefToBinaryData::is_content_id_Set() const{
    return m_content_id_isSet;
}

bool OAIRefToBinaryData::is_content_id_Valid() const{
    return m_content_id_isValid;
}

bool OAIRefToBinaryData::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_content_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIRefToBinaryData::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_content_id_isValid && true;
}

} // namespace OpenAPI
