/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIRedirectResponse.h
 *
 * 
 */

#ifndef OAIRedirectResponse_H
#define OAIRedirectResponse_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIRedirectResponse : public OAIObject {
public:
    OAIRedirectResponse();
    OAIRedirectResponse(QString json);
    ~OAIRedirectResponse() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getCause() const;
    void setCause(const QString &cause);
    bool is_cause_Set() const;
    bool is_cause_Valid() const;

    QString getTargetScp() const;
    void setTargetScp(const QString &target_scp);
    bool is_target_scp_Set() const;
    bool is_target_scp_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString cause;
    bool m_cause_isSet;
    bool m_cause_isValid;

    QString target_scp;
    bool m_target_scp_isSet;
    bool m_target_scp_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIRedirectResponse)

#endif // OAIRedirectResponse_H
