/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISmfChangeIndication_anyOf.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAISmfChangeIndication_anyOf::OAISmfChangeIndication_anyOf(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISmfChangeIndication_anyOf::OAISmfChangeIndication_anyOf() {
    this->initializeModel();
}

OAISmfChangeIndication_anyOf::~OAISmfChangeIndication_anyOf() {}

void OAISmfChangeIndication_anyOf::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAISmfChangeIndication_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAISmfChangeIndication_anyOf::fromJson(QString jsonString) {
    
    if ( jsonString.compare("CHANGED", Qt::CaseInsensitive) == 0) {
        m_value = eOAISmfChangeIndication_anyOf::CHANGED;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("REMOVED", Qt::CaseInsensitive) == 0) {
        m_value = eOAISmfChangeIndication_anyOf::REMOVED;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAISmfChangeIndication_anyOf::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString OAISmfChangeIndication_anyOf::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAISmfChangeIndication_anyOf::CHANGED:
            val = "CHANGED";
            break;
        case eOAISmfChangeIndication_anyOf::REMOVED:
            val = "REMOVED";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAISmfChangeIndication_anyOf::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAISmfChangeIndication_anyOf::eOAISmfChangeIndication_anyOf OAISmfChangeIndication_anyOf::getValue() const {
    return m_value;
}

void OAISmfChangeIndication_anyOf::setValue(const OAISmfChangeIndication_anyOf::eOAISmfChangeIndication_anyOf& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAISmfChangeIndication_anyOf::isSet() const {
    
    return m_value_isSet;
}

bool OAISmfChangeIndication_anyOf::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
