/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIStationaryIndication_anyOf.h
 *
 * 
 */

#ifndef OAIStationaryIndication_anyOf_H
#define OAIStationaryIndication_anyOf_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIStationaryIndication_anyOf : public OAIEnum {
public:
    OAIStationaryIndication_anyOf();
    OAIStationaryIndication_anyOf(QString json);
    ~OAIStationaryIndication_anyOf() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAIStationaryIndication_anyOf {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        STATIONARY, 
        MOBILE
    };
    OAIStationaryIndication_anyOf::eOAIStationaryIndication_anyOf getValue() const;
    void setValue(const OAIStationaryIndication_anyOf::eOAIStationaryIndication_anyOf& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAIStationaryIndication_anyOf m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIStationaryIndication_anyOf)

#endif // OAIStationaryIndication_anyOf_H
