/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISensorMeasurement_anyOf.h
 *
 * 
 */

#ifndef OAISensorMeasurement_anyOf_H
#define OAISensorMeasurement_anyOf_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAISensorMeasurement_anyOf : public OAIEnum {
public:
    OAISensorMeasurement_anyOf();
    OAISensorMeasurement_anyOf(QString json);
    ~OAISensorMeasurement_anyOf() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAISensorMeasurement_anyOf {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        BAROMETRIC_PRESSURE, 
        UE_SPEED, 
        UE_ORIENTATION
    };
    OAISensorMeasurement_anyOf::eOAISensorMeasurement_anyOf getValue() const;
    void setValue(const OAISensorMeasurement_anyOf::eOAISensorMeasurement_anyOf& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAISensorMeasurement_anyOf m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISensorMeasurement_anyOf)

#endif // OAISensorMeasurement_anyOf_H
