/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIStatusChange_anyOf.h
 *
 * 
 */

#ifndef OAIStatusChange_anyOf_H
#define OAIStatusChange_anyOf_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIStatusChange_anyOf : public OAIEnum {
public:
    OAIStatusChange_anyOf();
    OAIStatusChange_anyOf(QString json);
    ~OAIStatusChange_anyOf() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAIStatusChange_anyOf {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        UNAVAILABLE, 
        AVAILABLE
    };
    OAIStatusChange_anyOf::eOAIStatusChange_anyOf getValue() const;
    void setValue(const OAIStatusChange_anyOf::eOAIStatusChange_anyOf& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAIStatusChange_anyOf m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIStatusChange_anyOf)

#endif // OAIStatusChange_anyOf_H
