/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAITrafficProfile_anyOf.h
 *
 * 
 */

#ifndef OAITrafficProfile_anyOf_H
#define OAITrafficProfile_anyOf_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAITrafficProfile_anyOf : public OAIEnum {
public:
    OAITrafficProfile_anyOf();
    OAITrafficProfile_anyOf(QString json);
    ~OAITrafficProfile_anyOf() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAITrafficProfile_anyOf {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        SINGLE_TRANS_UL, 
        SINGLE_TRANS_DL, 
        DUAL_TRANS_UL_FIRST, 
        DUAL_TRANS_DL_FIRST, 
        MULTI_TRANS
    };
    OAITrafficProfile_anyOf::eOAITrafficProfile_anyOf getValue() const;
    void setValue(const OAITrafficProfile_anyOf::eOAITrafficProfile_anyOf& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAITrafficProfile_anyOf m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAITrafficProfile_anyOf)

#endif // OAITrafficProfile_anyOf_H
