/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAITransferReason_anyOf.h
 *
 * 
 */

#ifndef OAITransferReason_anyOf_H
#define OAITransferReason_anyOf_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAITransferReason_anyOf : public OAIEnum {
public:
    OAITransferReason_anyOf();
    OAITransferReason_anyOf(QString json);
    ~OAITransferReason_anyOf() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAITransferReason_anyOf {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        INIT_REG, 
        MOBI_REG, 
        MOBI_REG_UE_VALIDATED
    };
    OAITransferReason_anyOf::eOAITransferReason_anyOf getValue() const;
    void setValue(const OAITransferReason_anyOf::eOAITransferReason_anyOf& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAITransferReason_anyOf m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAITransferReason_anyOf)

#endif // OAITransferReason_anyOf_H
