/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIUeContextTransferReqData.h
 *
 * 
 */

#ifndef OAIUeContextTransferReqData_H
#define OAIUeContextTransferReqData_H

#include <QJsonObject>

#include "OAIAccessType.h"
#include "OAIN1MessageContainer.h"
#include "OAIPlmnId.h"
#include "OAITransferReason.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIUeContextTransferReqData : public OAIObject {
public:
    OAIUeContextTransferReqData();
    OAIUeContextTransferReqData(QString json);
    ~OAIUeContextTransferReqData() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAITransferReason getReason() const;
    void setReason(const OAITransferReason &reason);
    bool is_reason_Set() const;
    bool is_reason_Valid() const;

    OAIAccessType getAccessType() const;
    void setAccessType(const OAIAccessType &access_type);
    bool is_access_type_Set() const;
    bool is_access_type_Valid() const;

    OAIPlmnId getPlmnId() const;
    void setPlmnId(const OAIPlmnId &plmn_id);
    bool is_plmn_id_Set() const;
    bool is_plmn_id_Valid() const;

    OAIN1MessageContainer getRegRequest() const;
    void setRegRequest(const OAIN1MessageContainer &reg_request);
    bool is_reg_request_Set() const;
    bool is_reg_request_Valid() const;

    QString getSupportedFeatures() const;
    void setSupportedFeatures(const QString &supported_features);
    bool is_supported_features_Set() const;
    bool is_supported_features_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAITransferReason reason;
    bool m_reason_isSet;
    bool m_reason_isValid;

    OAIAccessType access_type;
    bool m_access_type_isSet;
    bool m_access_type_isValid;

    OAIPlmnId plmn_id;
    bool m_plmn_id_isSet;
    bool m_plmn_id_isValid;

    OAIN1MessageContainer reg_request;
    bool m_reg_request_isSet;
    bool m_reg_request_isValid;

    QString supported_features;
    bool m_supported_features_isSet;
    bool m_supported_features_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIUeContextTransferReqData)

#endif // OAIUeContextTransferReqData_H
