/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIUeContextCreateError.h
 *
 * 
 */

#ifndef OAIUeContextCreateError_H
#define OAIUeContextCreateError_H

#include <QJsonObject>

#include "OAIN2InfoContent.h"
#include "OAINgApCause.h"
#include "OAIProblemDetails.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIUeContextCreateError : public OAIObject {
public:
    OAIUeContextCreateError();
    OAIUeContextCreateError(QString json);
    ~OAIUeContextCreateError() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIProblemDetails getError() const;
    void setError(const OAIProblemDetails &error);
    bool is_error_Set() const;
    bool is_error_Valid() const;

    OAINgApCause getNgapCause() const;
    void setNgapCause(const OAINgApCause &ngap_cause);
    bool is_ngap_cause_Set() const;
    bool is_ngap_cause_Valid() const;

    OAIN2InfoContent getTargetToSourceFailureData() const;
    void setTargetToSourceFailureData(const OAIN2InfoContent &target_to_source_failure_data);
    bool is_target_to_source_failure_data_Set() const;
    bool is_target_to_source_failure_data_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIProblemDetails error;
    bool m_error_isSet;
    bool m_error_isValid;

    OAINgApCause ngap_cause;
    bool m_ngap_cause_isSet;
    bool m_ngap_cause_isValid;

    OAIN2InfoContent target_to_source_failure_data;
    bool m_target_to_source_failure_data_isSet;
    bool m_target_to_source_failure_data_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIUeContextCreateError)

#endif // OAIUeContextCreateError_H
