/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIUeContextTransferStatus_anyOf.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIUeContextTransferStatus_anyOf::OAIUeContextTransferStatus_anyOf(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIUeContextTransferStatus_anyOf::OAIUeContextTransferStatus_anyOf() {
    this->initializeModel();
}

OAIUeContextTransferStatus_anyOf::~OAIUeContextTransferStatus_anyOf() {}

void OAIUeContextTransferStatus_anyOf::initializeModel() {

    m_value_isSet = false;
    m_value_isValid = false;
    m_value = eOAIUeContextTransferStatus_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
}

void OAIUeContextTransferStatus_anyOf::fromJson(QString jsonString) {
    
    if ( jsonString.compare("TRANSFERRED", Qt::CaseInsensitive) == 0) {
        m_value = eOAIUeContextTransferStatus_anyOf::TRANSFERRED;
        m_value_isSet = m_value_isValid = true;
    }
    else if ( jsonString.compare("NOT_TRANSFERRED", Qt::CaseInsensitive) == 0) {
        m_value = eOAIUeContextTransferStatus_anyOf::NOT_TRANSFERRED;
        m_value_isSet = m_value_isValid = true;
    }
}

void OAIUeContextTransferStatus_anyOf::fromJsonValue(QJsonValue json) {
fromJson(json.toString());
}

QString OAIUeContextTransferStatus_anyOf::asJson() const {
    
    QString val;
    switch (m_value){
        case eOAIUeContextTransferStatus_anyOf::TRANSFERRED:
            val = "TRANSFERRED";
            break;
        case eOAIUeContextTransferStatus_anyOf::NOT_TRANSFERRED:
            val = "NOT_TRANSFERRED";
            break;
        default:
            break;
    }
    return val;
}

QJsonValue OAIUeContextTransferStatus_anyOf::asJsonValue() const {
    
    return QJsonValue(asJson());
}


OAIUeContextTransferStatus_anyOf::eOAIUeContextTransferStatus_anyOf OAIUeContextTransferStatus_anyOf::getValue() const {
    return m_value;
}

void OAIUeContextTransferStatus_anyOf::setValue(const OAIUeContextTransferStatus_anyOf::eOAIUeContextTransferStatus_anyOf& value){
    m_value = value;
    m_value_isSet = true;
}
bool OAIUeContextTransferStatus_anyOf::isSet() const {
    
    return m_value_isSet;
}

bool OAIUeContextTransferStatus_anyOf::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_value_isValid;
}

} // namespace OpenAPI
