/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIUeRegStatusUpdateRspData.h
 *
 * 
 */

#ifndef OAIUeRegStatusUpdateRspData_H
#define OAIUeRegStatusUpdateRspData_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIUeRegStatusUpdateRspData : public OAIObject {
public:
    OAIUeRegStatusUpdateRspData();
    OAIUeRegStatusUpdateRspData(QString json);
    ~OAIUeRegStatusUpdateRspData() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    bool isRegStatusTransferComplete() const;
    void setRegStatusTransferComplete(const bool &reg_status_transfer_complete);
    bool is_reg_status_transfer_complete_Set() const;
    bool is_reg_status_transfer_complete_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    bool reg_status_transfer_complete;
    bool m_reg_status_transfer_complete_isSet;
    bool m_reg_status_transfer_complete_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIUeRegStatusUpdateRspData)

#endif // OAIUeRegStatusUpdateRspData_H
