/*
 * Namf_Communication
 *
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel
import (
"amf.com/amfcommon"
)

// NfType - NF types known to NRF
type NfType struct {
}

// AssertNfTypeRequired checks if the required fields are not zero-ed
func AssertNfTypeRequired(obj NfType) error {
	return nil
}

// AssertRecurseNfTypeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NfType (e.g. [][]NfType), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseNfTypeRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNfType, ok := obj.(NfType)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertNfTypeRequired(aNfType)
	})
}
