/*
 * Namf_Communication
 *
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel
import (
"amf.com/amfcommon"
)

type ReportAmountMdtAnyOf string

// List of ReportAmountMdtAnyOf
const (
	REPORTAMOUNTMDTANYOF__1 ReportAmountMdtAnyOf = "1"
	REPORTAMOUNTMDTANYOF__2 ReportAmountMdtAnyOf = "2"
	REPORTAMOUNTMDTANYOF__4 ReportAmountMdtAnyOf = "4"
	REPORTAMOUNTMDTANYOF__8 ReportAmountMdtAnyOf = "8"
	REPORTAMOUNTMDTANYOF__16 ReportAmountMdtAnyOf = "16"
	REPORTAMOUNTMDTANYOF__32 ReportAmountMdtAnyOf = "32"
	REPORTAMOUNTMDTANYOF__64 ReportAmountMdtAnyOf = "64"
	REPORTAMOUNTMDTANYOF_INFINITY ReportAmountMdtAnyOf = "infinity"
)

// AssertReportAmountMdtAnyOfRequired checks if the required fields are not zero-ed
func AssertReportAmountMdtAnyOfRequired(obj ReportAmountMdtAnyOf) error {
	return nil
}

// AssertRecurseReportAmountMdtAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ReportAmountMdtAnyOf (e.g. [][]ReportAmountMdtAnyOf), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseReportAmountMdtAnyOfRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aReportAmountMdtAnyOf, ok := obj.(ReportAmountMdtAnyOf)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertReportAmountMdtAnyOfRequired(aReportAmountMdtAnyOf)
	})
}
