/*
 * Namf_Location
 *
 * AMF Location Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel

import (
"amf.com/amfcommon"
)

type ResponseTime struct {
}

// AssertResponseTimeRequired checks if the required fields are not zero-ed
func AssertResponseTimeRequired(obj ResponseTime) error {
	return nil
}

// AssertRecurseResponseTimeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ResponseTime (e.g. [][]ResponseTime), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseResponseTimeRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aResponseTime, ok := obj.(ResponseTime)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertResponseTimeRequired(aResponseTime)
	})
}
