/*
 * Namf_Communication
 *
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel

import (
"amf.com/amfcommon"
)

type EpsNasCipheringAlgorithmAnyOf string

// List of EpsNasCipheringAlgorithmAnyOf
const (
	EPSNASCIPHERINGALGORITHMANYOF_EEA0 EpsNasCipheringAlgorithmAnyOf = "EEA0"
	EPSNASCIPHERINGALGORITHMANYOF_EEA1 EpsNasCipheringAlgorithmAnyOf = "EEA1"
	EPSNASCIPHERINGALGORITHMANYOF_EEA2 EpsNasCipheringAlgorithmAnyOf = "EEA2"
	EPSNASCIPHERINGALGORITHMANYOF_EEA3 EpsNasCipheringAlgorithmAnyOf = "EEA3"
)

// AssertEpsNasCipheringAlgorithmAnyOfRequired checks if the required fields are not zero-ed
func AssertEpsNasCipheringAlgorithmAnyOfRequired(obj EpsNasCipheringAlgorithmAnyOf) error {
	return nil
}

// AssertRecurseEpsNasCipheringAlgorithmAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of EpsNasCipheringAlgorithmAnyOf (e.g. [][]EpsNasCipheringAlgorithmAnyOf), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseEpsNasCipheringAlgorithmAnyOfRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aEpsNasCipheringAlgorithmAnyOf, ok := obj.(EpsNasCipheringAlgorithmAnyOf)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertEpsNasCipheringAlgorithmAnyOfRequired(aEpsNasCipheringAlgorithmAnyOf)
	})
}
