/*
 * Namf_Communication
 *
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel
import (
"amf.com/amfcommon"
)

type SbiBindingLevel struct {
}

// AssertSbiBindingLevelRequired checks if the required fields are not zero-ed
func AssertSbiBindingLevelRequired(obj SbiBindingLevel) error {
	return nil
}

// AssertRecurseSbiBindingLevelRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SbiBindingLevel (e.g. [][]SbiBindingLevel), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseSbiBindingLevelRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSbiBindingLevel, ok := obj.(SbiBindingLevel)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertSbiBindingLevelRequired(aSbiBindingLevel)
	})
}
