/*
 * Namf_Communication
 *
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel

import (
	"amf.com/amfcommon"
)

type AssignEbiFailed struct {
	PduSessionId int32 `json:"pduSessionId"`

	FailedArpList []Arp `json:"failedArpList,omitempty"`
}

// AssertAssignEbiFailedRequired checks if the required fields are not zero-ed
func AssertAssignEbiFailedRequired(obj AssignEbiFailed) error {
	elements := map[string]interface{}{
		"pduSessionId": obj.PduSessionId,
	}
	for name, el := range elements {
		if isZero := amfcommon.IsZeroValue(el); isZero {
			return &amfcommon.RequiredError{Field: name}
		}
	}

	for _, el := range obj.FailedArpList {
		if err := AssertArpRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseAssignEbiFailedRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AssignEbiFailed (e.g. [][]AssignEbiFailed), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseAssignEbiFailedRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAssignEbiFailed, ok := obj.(AssignEbiFailed)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertAssignEbiFailedRequired(aAssignEbiFailed)
	})
}
