/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel
import (
"amf.com/amfcommon"
)

type CmState struct {
}

// AssertCmStateRequired checks if the required fields are not zero-ed
func AssertCmStateRequired(obj CmState) error {
	return nil
}

// AssertRecurseCmStateRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CmState (e.g. [][]CmState), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseCmStateRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCmState, ok := obj.(CmState)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertCmStateRequired(aCmState)
	})
}
