/*
 * Namf_Communication
 *
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel
import (
"amf.com/amfcommon"
)

type UeContextCancelRelocateData struct {

	Supi string `json:"supi,omitempty"`

	RelocationCancelRequest RefToBinaryData `json:"relocationCancelRequest"`
}

// AssertUeContextCancelRelocateDataRequired checks if the required fields are not zero-ed
func AssertUeContextCancelRelocateDataRequired(obj UeContextCancelRelocateData) error {
	elements := map[string]interface{}{
		"relocationCancelRequest": obj.RelocationCancelRequest,
	}
	for name, el := range elements {
		if isZero := amfcommon.IsZeroValue(el); isZero {
			return &amfcommon.RequiredError{Field: name}
		}
	}

	if err := AssertRefToBinaryDataRequired(obj.RelocationCancelRequest); err != nil {
		return err
	}
	return nil
}

// AssertRecurseUeContextCancelRelocateDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UeContextCancelRelocateData (e.g. [][]UeContextCancelRelocateData), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseUeContextCancelRelocateDataRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUeContextCancelRelocateData, ok := obj.(UeContextCancelRelocateData)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertUeContextCancelRelocateDataRequired(aUeContextCancelRelocateData)
	})
}
