/*
 * Namf_Location
 *
 * AMF Location Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel

import (
"amf.com/amfcommon"
)

type PositioningModeAnyOf string

// List of PositioningModeAnyOf
const (
	POSITIONINGMODEANYOF_UE_BASED PositioningModeAnyOf = "UE_BASED"
	POSITIONINGMODEANYOF_UE_ASSISTED PositioningModeAnyOf = "UE_ASSISTED"
	POSITIONINGMODEANYOF_CONVENTIONAL PositioningModeAnyOf = "CONVENTIONAL"
)

// AssertPositioningModeAnyOfRequired checks if the required fields are not zero-ed
func AssertPositioningModeAnyOfRequired(obj PositioningModeAnyOf) error {
	return nil
}

// AssertRecursePositioningModeAnyOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PositioningModeAnyOf (e.g. [][]PositioningModeAnyOf), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecursePositioningModeAnyOfRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPositioningModeAnyOf, ok := obj.(PositioningModeAnyOf)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertPositioningModeAnyOfRequired(aPositioningModeAnyOf)
	})
}
