/*
 * Namf_Location
 *
 * AMF Location Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel

import (
"amf.com/amfcommon"
)

type VerticalDirection string

// List of VerticalDirection
const (
	VERTICALDIRECTION_UPWARD VerticalDirection = "UPWARD"
	VERTICALDIRECTION_DOWNWARD VerticalDirection = "DOWNWARD"
)

// AssertVerticalDirectionRequired checks if the required fields are not zero-ed
func AssertVerticalDirectionRequired(obj VerticalDirection) error {
	return nil
}

// AssertRecurseVerticalDirectionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of VerticalDirection (e.g. [][]VerticalDirection), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseVerticalDirectionRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aVerticalDirection, ok := obj.(VerticalDirection)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertVerticalDirectionRequired(aVerticalDirection)
	})
}
