/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel

import (
"amf.com/amfcommon"
)

type AmfUpdateEventSubscriptionItem struct {

	Op string `json:"op"`

	Path string `json:"path"`

	Value AmfEvent `json:"value,omitempty"`
}

// AssertAmfUpdateEventSubscriptionItemRequired checks if the required fields are not zero-ed
func AssertAmfUpdateEventSubscriptionItemRequired(obj AmfUpdateEventSubscriptionItem) error {
	elements := map[string]interface{}{
		"op": obj.Op,
		"path": obj.Path,
	}
	for name, el := range elements {
		if isZero := amfcommon.IsZeroValue(el); isZero {
			return &amfcommon.RequiredError{Field: name}
		}
	}

	if err := AssertAmfEventRequired(obj.Value); err != nil {
		return err
	}
	return nil
}

// AssertRecurseAmfUpdateEventSubscriptionItemRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AmfUpdateEventSubscriptionItem (e.g. [][]AmfUpdateEventSubscriptionItem), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseAmfUpdateEventSubscriptionItemRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAmfUpdateEventSubscriptionItem, ok := obj.(AmfUpdateEventSubscriptionItem)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertAmfUpdateEventSubscriptionItemRequired(aAmfUpdateEventSubscriptionItem)
	})
}
