/*
 * Namf_Communication
 *
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel
import (
"amf.com/amfcommon"
)

// TransportProtocol - Possible values are - UDP: User Datagram Protocol. - TCP: Transmission Control Protocol. 
type TransportProtocol struct {
}

// AssertTransportProtocolRequired checks if the required fields are not zero-ed
func AssertTransportProtocolRequired(obj TransportProtocol) error {
	return nil
}

// AssertRecurseTransportProtocolRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TransportProtocol (e.g. [][]TransportProtocol), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseTransportProtocolRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTransportProtocol, ok := obj.(TransportProtocol)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertTransportProtocolRequired(aTransportProtocol)
	})
}
