/*
 * Namf_Communication
 *
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel
import (
"amf.com/amfcommon"
)

type SensorMeasurement struct {
}

// AssertSensorMeasurementRequired checks if the required fields are not zero-ed
func AssertSensorMeasurementRequired(obj SensorMeasurement) error {
	return nil
}

// AssertRecurseSensorMeasurementRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SensorMeasurement (e.g. [][]SensorMeasurement), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseSensorMeasurementRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSensorMeasurement, ok := obj.(SensorMeasurement)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertSensorMeasurementRequired(aSensorMeasurement)
	})
}
