/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel

import (
"amf.com/amfcommon"
)

type UeReachability struct {
}

// AssertUeReachabilityRequired checks if the required fields are not zero-ed
func AssertUeReachabilityRequired(obj UeReachability) error {
	return nil
}

// AssertRecurseUeReachabilityRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UeReachability (e.g. [][]UeReachability), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseUeReachabilityRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUeReachability, ok := obj.(UeReachability)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertUeReachabilityRequired(aUeReachability)
	})
}
