/*
 * Namf_Communication
 *
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel

import (
"amf.com/amfcommon"
)

type AllowedNssai struct {

	AllowedSnssaiList []AllowedSnssai `json:"allowedSnssaiList"`

	AccessType AccessType `json:"accessType"`
}

// AssertAllowedNssaiRequired checks if the required fields are not zero-ed
func AssertAllowedNssaiRequired(obj AllowedNssai) error {
	elements := map[string]interface{}{
		"allowedSnssaiList": obj.AllowedSnssaiList,
		"accessType": obj.AccessType,
	}
	for name, el := range elements {
		if isZero := amfcommon.IsZeroValue(el); isZero {
			return &amfcommon.RequiredError{Field: name}
		}
	}

	for _, el := range obj.AllowedSnssaiList {
		if err := AssertAllowedSnssaiRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseAllowedNssaiRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AllowedNssai (e.g. [][]AllowedNssai), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseAllowedNssaiRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAllowedNssai, ok := obj.(AllowedNssai)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertAllowedNssaiRequired(aAllowedNssai)
	})
}
