/*
 * Namf_Communication
 *
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel
import (
"amf.com/amfcommon"
)

type JobType struct {
}

// AssertJobTypeRequired checks if the required fields are not zero-ed
func AssertJobTypeRequired(obj JobType) error {
	return nil
}

// AssertRecurseJobTypeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of JobType (e.g. [][]JobType), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseJobTypeRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aJobType, ok := obj.(JobType)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertJobTypeRequired(aJobType)
	})
}
