/*
 * Namf_Communication
 *
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel
import (
"amf.com/amfcommon"
)

type SmsSupport struct {
}

// AssertSmsSupportRequired checks if the required fields are not zero-ed
func AssertSmsSupportRequired(obj SmsSupport) error {
	return nil
}

// AssertRecurseSmsSupportRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SmsSupport (e.g. [][]SmsSupport), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseSmsSupportRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSmsSupport, ok := obj.(SmsSupport)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertSmsSupportRequired(aSmsSupport)
	})
}
