/*
 * Namf_Location
 *
 * AMF Location Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel

import (
	"amf.com/amfcommon"
)

type AccuracyFulfilmentIndicator struct {
}

// AssertAccuracyFulfilmentIndicatorRequired checks if the required fields are not zero-ed
func AssertAccuracyFulfilmentIndicatorRequired(obj AccuracyFulfilmentIndicator) error {
	return nil
}

// AssertRecurseAccuracyFulfilmentIndicatorRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AccuracyFulfilmentIndicator (e.g. [][]AccuracyFulfilmentIndicator), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseAccuracyFulfilmentIndicatorRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAccuracyFulfilmentIndicator, ok := obj.(AccuracyFulfilmentIndicator)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertAccuracyFulfilmentIndicatorRequired(aAccuracyFulfilmentIndicator)
	})
}
