/*
 * Namf_Location
 *
 * AMF Location Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel

import (
	"amf.com/amfcommon"
)

type VelocityRequested struct {
}

// AssertVelocityRequestedRequired checks if the required fields are not zero-ed
func AssertVelocityRequestedRequired(obj VelocityRequested) error {
	return nil
}

// AssertRecurseVelocityRequestedRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of VelocityRequested (e.g. [][]VelocityRequested), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseVelocityRequestedRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aVelocityRequested, ok := obj.(VelocityRequested)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertVelocityRequestedRequired(aVelocityRequested)
	})
}
