/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmodel
import (
"amf.com/amfcommon"
)

type UeidExt struct {

	Supi string `json:"supi,omitempty"`

	Gpsi string `json:"gpsi,omitempty"`
}

// AssertUeidExtRequired checks if the required fields are not zero-ed
func AssertUeidExtRequired(obj UeidExt) error {
	return nil
}

// AssertRecurseUeidExtRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UeidExt (e.g. [][]UeidExt), otherwise amfcommon.ErrTypeAssertionError is thrown.
func AssertRecurseUeidExtRequired(objSlice interface{}) error {
	return amfcommon.AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUeidExt, ok := obj.(UeidExt)
		if !ok {
			return amfcommon.ErrTypeAssertionError
		}
		return AssertUeidExtRequired(aUeidExt)
	})
}
