/**
 * Namf_EventExposure
 * AMF Event Exposure Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIEESubscriptionsCollectionDocumentApiRequest_H
#define OAI_OAIEESubscriptionsCollectionDocumentApiRequest_H

#include <QObject>
#include <QStringList>
#include <QMultiMap>
#include <QNetworkReply>
#include <QSharedPointer>

#include <qhttpengine/socket.h>
#include "OAIAmfCreateEventSubscription.h"
#include "OAIAmfCreatedEventSubscription.h"
#include "OAIProblemDetails.h"
#include "OAIRedirectResponse.h"
#include <QString>
#include "OAIEESubscriptionsCollectionDocumentApiHandler.h"

namespace OpenAPI {

class OAIEESubscriptionsCollectionDocumentApiRequest : public QObject
{
    Q_OBJECT

public:
    OAIEESubscriptionsCollectionDocumentApiRequest(QHttpEngine::Socket *s, QSharedPointer<OAIEESubscriptionsCollectionDocumentApiHandler> handler);
    virtual ~OAIEESubscriptionsCollectionDocumentApiRequest();

    void createSubscriptionRequest();
    

    void createSubscriptionResponse(const OAIAmfCreatedEventSubscription& res);
    

    void createSubscriptionError(const OAIAmfCreatedEventSubscription& res, QNetworkReply::NetworkError error_type, QString& error_str);
    

    void sendCustomResponse(QByteArray & res, QNetworkReply::NetworkError error_type);

    void sendCustomResponse(QIODevice *res, QNetworkReply::NetworkError error_type);

    QMap<QString, QString> getRequestHeaders() const;

    QHttpEngine::Socket* getRawSocket();

    void setResponseHeaders(const QMultiMap<QString,QString>& headers);

signals:
    void createSubscription(OAIAmfCreateEventSubscription oai_amf_create_event_subscription);
    

private:
    QMap<QString, QString> requestHeaders;
    QMap<QString, QString> responseHeaders;
    QHttpEngine::Socket  *socket;
    QSharedPointer<OAIEESubscriptionsCollectionDocumentApiHandler> handler;

    inline void setSocketResponseHeaders(){
        QHttpEngine::Socket::HeaderMap resHeaders;
        for(auto itr = responseHeaders.begin(); itr != responseHeaders.end(); ++itr) {
            resHeaders.insert(itr.key().toUtf8(), itr.value().toUtf8());
        }
        socket->setHeaders(resHeaders);
    }
};

}

#endif // OAI_OAIEESubscriptionsCollectionDocumentApiRequest_H
