/**
 * Namf_Communication
 * AMF Communication Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.5
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiRequest_H
#define OAI_OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiRequest_H

#include <QObject>
#include <QStringList>
#include <QMultiMap>
#include <QNetworkReply>
#include <QSharedPointer>

#include <qhttpengine/socket.h>
#include "OAIProblemDetails.h"
#include "OAIRedirectResponse.h"
#include <QString>
#include "OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiHandler.h"

namespace OpenAPI {

class OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiRequest : public QObject
{
    Q_OBJECT

public:
    OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiRequest(QHttpEngine::Socket *s, QSharedPointer<OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiHandler> handler);
    virtual ~OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiRequest();

    void nonUeN2InfoUnSubscribeRequest(const QString& n2_notify_subscription_id);
    

    void nonUeN2InfoUnSubscribeResponse();
    

    void nonUeN2InfoUnSubscribeError(QNetworkReply::NetworkError error_type, QString& error_str);
    

    void sendCustomResponse(QByteArray & res, QNetworkReply::NetworkError error_type);

    void sendCustomResponse(QIODevice *res, QNetworkReply::NetworkError error_type);

    QMap<QString, QString> getRequestHeaders() const;

    QHttpEngine::Socket* getRawSocket();

    void setResponseHeaders(const QMultiMap<QString,QString>& headers);

signals:
    void nonUeN2InfoUnSubscribe(QString n2_notify_subscription_id);
    

private:
    QMap<QString, QString> requestHeaders;
    QMap<QString, QString> responseHeaders;
    QHttpEngine::Socket  *socket;
    QSharedPointer<OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiHandler> handler;

    inline void setSocketResponseHeaders(){
        QHttpEngine::Socket::HeaderMap resHeaders;
        for(auto itr = responseHeaders.begin(); itr != responseHeaders.end(); ++itr) {
            resHeaders.insert(itr.key().toUtf8(), itr.value().toUtf8());
        }
        socket->setHeaders(resHeaders);
    }
};

}

#endif // OAI_OAINonUEN2MessageNotificationIndividualSubscriptionDocumentApiRequest_H
