/*
 * Namf_MT
 *
 * AMF Mobile Terminated Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amfmt

import (
	"amf.com/amfcommon"
	"github.com/gorilla/mux"
)

func Routeramfmt(router *mux.Router) *mux.Router {

	UeContextDocumentApiService := NewUeContextDocumentApiService()
	UeContextDocumentApiController := NewUeContextDocumentApiController(UeContextDocumentApiService)

	UeReachIndDocumentApiService := NewUeReachIndDocumentApiService()
	UeReachIndDocumentApiController := NewUeReachIndDocumentApiController(UeReachIndDocumentApiService)

	router = amfcommon.AddRouter(router, UeContextDocumentApiController, UeReachIndDocumentApiController)

	return router
}
