/*
 * Namf_Location
 *
 * AMF Location Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package amflocation

import (
"amf.com/amfcommon"
	"github.com/gorilla/mux"
	"log"
	"net/http"

	
)

func Routeramflocation(router *mux.Router) *mux.Router {
	

	IndividualUEContextDocumentApiService := NewIndividualUEContextDocumentApiService()
	IndividualUEContextDocumentApiController := NewIndividualUEContextDocumentApiController(IndividualUEContextDocumentApiService)

	router =amfcommon.AddRouter(router,IndividualUEContextDocumentApiController) 

	return router
}
